/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE390_Error_Without_Action__fopen_05_good();");
	CWE390_Error_Without_Action__fopen_05_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_05_good();");
	CWE390_Error_Without_Action__fgets_char_05_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_11_good();");
	CWE390_Error_Without_Action__fopen_11_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_07_good();");
	CWE390_Error_Without_Action__sqrt_07_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_03_good();");
	CWE390_Error_Without_Action__fopen_03_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_02_good();");
	CWE390_Error_Without_Action__fgets_char_02_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_10_good();");
	CWE390_Error_Without_Action__sqrt_10_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_01_good();");
	CWE390_Error_Without_Action__fopen_01_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_17_good();");
	CWE390_Error_Without_Action__fgets_char_17_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_14_good();");
	CWE390_Error_Without_Action__fopen_14_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_13_good();");
	CWE390_Error_Without_Action__sqrt_13_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_04_good();");
	CWE390_Error_Without_Action__fopen_04_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_08_good();");
	CWE390_Error_Without_Action__sqrt_08_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_16_good();");
	CWE390_Error_Without_Action__sqrt_16_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_14_good();");
	CWE390_Error_Without_Action__sqrt_14_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_18_good();");
	CWE390_Error_Without_Action__fopen_18_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_03_good();");
	CWE390_Error_Without_Action__sqrt_03_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_06_good();");
	CWE390_Error_Without_Action__fopen_06_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_12_good();");
	CWE390_Error_Without_Action__sqrt_12_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_12_good();");
	CWE390_Error_Without_Action__fopen_12_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_10_good();");
	CWE390_Error_Without_Action__fopen_10_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_05_good();");
	CWE390_Error_Without_Action__sqrt_05_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_11_good();");
	CWE390_Error_Without_Action__fgets_char_11_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_11_good();");
	CWE390_Error_Without_Action__sqrt_11_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_14_good();");
	CWE390_Error_Without_Action__fgets_char_14_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_02_good();");
	CWE390_Error_Without_Action__sqrt_02_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_09_good();");
	CWE390_Error_Without_Action__fgets_char_09_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_13_good();");
	CWE390_Error_Without_Action__fopen_13_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_12_good();");
	CWE390_Error_Without_Action__fgets_char_12_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_07_good();");
	CWE390_Error_Without_Action__fopen_07_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_17_good();");
	CWE390_Error_Without_Action__sqrt_17_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_08_good();");
	CWE390_Error_Without_Action__fgets_char_08_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_09_good();");
	CWE390_Error_Without_Action__fopen_09_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_18_good();");
	CWE390_Error_Without_Action__sqrt_18_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_04_good();");
	CWE390_Error_Without_Action__sqrt_04_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_04_good();");
	CWE390_Error_Without_Action__fgets_char_04_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_01_good();");
	CWE390_Error_Without_Action__fgets_char_01_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_17_good();");
	CWE390_Error_Without_Action__fopen_17_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_07_good();");
	CWE390_Error_Without_Action__fgets_char_07_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_09_good();");
	CWE390_Error_Without_Action__sqrt_09_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_16_good();");
	CWE390_Error_Without_Action__fgets_char_16_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_15_good();");
	CWE390_Error_Without_Action__fopen_15_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_06_good();");
	CWE390_Error_Without_Action__fgets_char_06_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_06_good();");
	CWE390_Error_Without_Action__sqrt_06_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_08_good();");
	CWE390_Error_Without_Action__fopen_08_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_18_good();");
	CWE390_Error_Without_Action__fgets_char_18_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_01_good();");
	CWE390_Error_Without_Action__sqrt_01_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_10_good();");
	CWE390_Error_Without_Action__fgets_char_10_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_16_good();");
	CWE390_Error_Without_Action__fopen_16_good();

	printLine("Calling CWE390_Error_Without_Action__fopen_02_good();");
	CWE390_Error_Without_Action__fopen_02_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_13_good();");
	CWE390_Error_Without_Action__fgets_char_13_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_03_good();");
	CWE390_Error_Without_Action__fgets_char_03_good();

	printLine("Calling CWE390_Error_Without_Action__sqrt_15_good();");
	CWE390_Error_Without_Action__sqrt_15_good();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_15_good();");
	CWE390_Error_Without_Action__fgets_char_15_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE390_Error_Without_Action__fopen_05_bad();");
	CWE390_Error_Without_Action__fopen_05_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_05_bad();");
	CWE390_Error_Without_Action__fgets_char_05_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_11_bad();");
	CWE390_Error_Without_Action__fopen_11_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_07_bad();");
	CWE390_Error_Without_Action__sqrt_07_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_03_bad();");
	CWE390_Error_Without_Action__fopen_03_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_02_bad();");
	CWE390_Error_Without_Action__fgets_char_02_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_10_bad();");
	CWE390_Error_Without_Action__sqrt_10_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_01_bad();");
	CWE390_Error_Without_Action__fopen_01_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_17_bad();");
	CWE390_Error_Without_Action__fgets_char_17_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_14_bad();");
	CWE390_Error_Without_Action__fopen_14_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_13_bad();");
	CWE390_Error_Without_Action__sqrt_13_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_04_bad();");
	CWE390_Error_Without_Action__fopen_04_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_08_bad();");
	CWE390_Error_Without_Action__sqrt_08_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_16_bad();");
	CWE390_Error_Without_Action__sqrt_16_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_14_bad();");
	CWE390_Error_Without_Action__sqrt_14_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_18_bad();");
	CWE390_Error_Without_Action__fopen_18_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_03_bad();");
	CWE390_Error_Without_Action__sqrt_03_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_06_bad();");
	CWE390_Error_Without_Action__fopen_06_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_12_bad();");
	CWE390_Error_Without_Action__sqrt_12_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_12_bad();");
	CWE390_Error_Without_Action__fopen_12_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_10_bad();");
	CWE390_Error_Without_Action__fopen_10_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_05_bad();");
	CWE390_Error_Without_Action__sqrt_05_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_11_bad();");
	CWE390_Error_Without_Action__fgets_char_11_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_11_bad();");
	CWE390_Error_Without_Action__sqrt_11_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_14_bad();");
	CWE390_Error_Without_Action__fgets_char_14_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_02_bad();");
	CWE390_Error_Without_Action__sqrt_02_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_09_bad();");
	CWE390_Error_Without_Action__fgets_char_09_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_13_bad();");
	CWE390_Error_Without_Action__fopen_13_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_12_bad();");
	CWE390_Error_Without_Action__fgets_char_12_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_07_bad();");
	CWE390_Error_Without_Action__fopen_07_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_17_bad();");
	CWE390_Error_Without_Action__sqrt_17_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_08_bad();");
	CWE390_Error_Without_Action__fgets_char_08_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_09_bad();");
	CWE390_Error_Without_Action__fopen_09_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_18_bad();");
	CWE390_Error_Without_Action__sqrt_18_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_04_bad();");
	CWE390_Error_Without_Action__sqrt_04_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_04_bad();");
	CWE390_Error_Without_Action__fgets_char_04_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_01_bad();");
	CWE390_Error_Without_Action__fgets_char_01_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_17_bad();");
	CWE390_Error_Without_Action__fopen_17_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_07_bad();");
	CWE390_Error_Without_Action__fgets_char_07_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_09_bad();");
	CWE390_Error_Without_Action__sqrt_09_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_16_bad();");
	CWE390_Error_Without_Action__fgets_char_16_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_15_bad();");
	CWE390_Error_Without_Action__fopen_15_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_06_bad();");
	CWE390_Error_Without_Action__fgets_char_06_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_06_bad();");
	CWE390_Error_Without_Action__sqrt_06_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_08_bad();");
	CWE390_Error_Without_Action__fopen_08_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_18_bad();");
	CWE390_Error_Without_Action__fgets_char_18_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_01_bad();");
	CWE390_Error_Without_Action__sqrt_01_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_10_bad();");
	CWE390_Error_Without_Action__fgets_char_10_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_16_bad();");
	CWE390_Error_Without_Action__fopen_16_bad();

	printLine("Calling CWE390_Error_Without_Action__fopen_02_bad();");
	CWE390_Error_Without_Action__fopen_02_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_13_bad();");
	CWE390_Error_Without_Action__fgets_char_13_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_03_bad();");
	CWE390_Error_Without_Action__fgets_char_03_bad();

	printLine("Calling CWE390_Error_Without_Action__sqrt_15_bad();");
	CWE390_Error_Without_Action__sqrt_15_bad();

	printLine("Calling CWE390_Error_Without_Action__fgets_char_15_bad();");
	CWE390_Error_Without_Action__fgets_char_15_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
