/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE401_Memory_Leak__strdup_char_22_good();");
	CWE401_Memory_Leak__strdup_char_22_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_13_good();");
	CWE401_Memory_Leak__strdup_char_13_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_17_good();");
	CWE401_Memory_Leak__strdup_char_17_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_14_good();");
	CWE401_Memory_Leak__strdup_char_14_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_18_good();");
	CWE401_Memory_Leak__strdup_char_18_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_65_good();");
	CWE401_Memory_Leak__strdup_char_65_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_54_good();");
	CWE401_Memory_Leak__strdup_char_54_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_09_good();");
	CWE401_Memory_Leak__strdup_char_09_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_11_good();");
	CWE401_Memory_Leak__strdup_char_11_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_44_good();");
	CWE401_Memory_Leak__strdup_char_44_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_10_good();");
	CWE401_Memory_Leak__strdup_char_10_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_41_good();");
	CWE401_Memory_Leak__strdup_char_41_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_21_good();");
	CWE401_Memory_Leak__strdup_char_21_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_03_good();");
	CWE401_Memory_Leak__strdup_char_03_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_42_good();");
	CWE401_Memory_Leak__strdup_char_42_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_05_good();");
	CWE401_Memory_Leak__strdup_char_05_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_16_good();");
	CWE401_Memory_Leak__strdup_char_16_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_31_good();");
	CWE401_Memory_Leak__strdup_char_31_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_52_good();");
	CWE401_Memory_Leak__strdup_char_52_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_01_good();");
	CWE401_Memory_Leak__strdup_char_01_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_15_good();");
	CWE401_Memory_Leak__strdup_char_15_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_67_good();");
	CWE401_Memory_Leak__strdup_char_67_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_06_good();");
	CWE401_Memory_Leak__strdup_char_06_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_02_good();");
	CWE401_Memory_Leak__strdup_char_02_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_32_good();");
	CWE401_Memory_Leak__strdup_char_32_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_04_good();");
	CWE401_Memory_Leak__strdup_char_04_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_63_good();");
	CWE401_Memory_Leak__strdup_char_63_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_68_good();");
	CWE401_Memory_Leak__strdup_char_68_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_53_good();");
	CWE401_Memory_Leak__strdup_char_53_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_64_good();");
	CWE401_Memory_Leak__strdup_char_64_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_34_good();");
	CWE401_Memory_Leak__strdup_char_34_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_08_good();");
	CWE401_Memory_Leak__strdup_char_08_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_45_good();");
	CWE401_Memory_Leak__strdup_char_45_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_07_good();");
	CWE401_Memory_Leak__strdup_char_07_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_51_good();");
	CWE401_Memory_Leak__strdup_char_51_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_66_good();");
	CWE401_Memory_Leak__strdup_char_66_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_61_good();");
	CWE401_Memory_Leak__strdup_char_61_good();

	printLine("Calling CWE401_Memory_Leak__strdup_char_12_good();");
	CWE401_Memory_Leak__strdup_char_12_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE401_Memory_Leak__strdup_char_22_bad();");
	CWE401_Memory_Leak__strdup_char_22_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_13_bad();");
	CWE401_Memory_Leak__strdup_char_13_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_17_bad();");
	CWE401_Memory_Leak__strdup_char_17_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_14_bad();");
	CWE401_Memory_Leak__strdup_char_14_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_18_bad();");
	CWE401_Memory_Leak__strdup_char_18_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_65_bad();");
	CWE401_Memory_Leak__strdup_char_65_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_54_bad();");
	CWE401_Memory_Leak__strdup_char_54_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_09_bad();");
	CWE401_Memory_Leak__strdup_char_09_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_11_bad();");
	CWE401_Memory_Leak__strdup_char_11_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_44_bad();");
	CWE401_Memory_Leak__strdup_char_44_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_10_bad();");
	CWE401_Memory_Leak__strdup_char_10_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_41_bad();");
	CWE401_Memory_Leak__strdup_char_41_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_21_bad();");
	CWE401_Memory_Leak__strdup_char_21_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_03_bad();");
	CWE401_Memory_Leak__strdup_char_03_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_42_bad();");
	CWE401_Memory_Leak__strdup_char_42_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_05_bad();");
	CWE401_Memory_Leak__strdup_char_05_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_16_bad();");
	CWE401_Memory_Leak__strdup_char_16_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_31_bad();");
	CWE401_Memory_Leak__strdup_char_31_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_52_bad();");
	CWE401_Memory_Leak__strdup_char_52_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_01_bad();");
	CWE401_Memory_Leak__strdup_char_01_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_15_bad();");
	CWE401_Memory_Leak__strdup_char_15_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_67_bad();");
	CWE401_Memory_Leak__strdup_char_67_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_06_bad();");
	CWE401_Memory_Leak__strdup_char_06_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_02_bad();");
	CWE401_Memory_Leak__strdup_char_02_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_32_bad();");
	CWE401_Memory_Leak__strdup_char_32_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_04_bad();");
	CWE401_Memory_Leak__strdup_char_04_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_63_bad();");
	CWE401_Memory_Leak__strdup_char_63_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_68_bad();");
	CWE401_Memory_Leak__strdup_char_68_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_53_bad();");
	CWE401_Memory_Leak__strdup_char_53_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_64_bad();");
	CWE401_Memory_Leak__strdup_char_64_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_34_bad();");
	CWE401_Memory_Leak__strdup_char_34_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_08_bad();");
	CWE401_Memory_Leak__strdup_char_08_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_45_bad();");
	CWE401_Memory_Leak__strdup_char_45_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_07_bad();");
	CWE401_Memory_Leak__strdup_char_07_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_51_bad();");
	CWE401_Memory_Leak__strdup_char_51_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_66_bad();");
	CWE401_Memory_Leak__strdup_char_66_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_61_bad();");
	CWE401_Memory_Leak__strdup_char_61_bad();

	printLine("Calling CWE401_Memory_Leak__strdup_char_12_bad();");
	CWE401_Memory_Leak__strdup_char_12_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
