// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE758_Undefined_Behavior__char_malloc_use_05_good();

	void CWE758_Undefined_Behavior__long_malloc_use_13_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_18_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_14_good();

	void CWE758_Undefined_Behavior__int_malloc_use_18_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_11_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_16_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_05_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_14_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_06_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_04_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_18_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_16_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_01_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_13_good();

	void CWE758_Undefined_Behavior__long_alloca_use_01_good();

	void CWE758_Undefined_Behavior__char_alloca_use_08_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_09_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int_alloca_use_16_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_10_good();

	void CWE758_Undefined_Behavior__int_alloca_use_03_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_03_good();

	void CWE758_Undefined_Behavior__char_alloca_use_14_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_10_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_07_good();

	void CWE758_Undefined_Behavior__char_malloc_use_16_good();

	void CWE758_Undefined_Behavior__w32_return_implicit_01_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_03_good();

	void CWE758_Undefined_Behavior__long_malloc_use_07_good();

	void CWE758_Undefined_Behavior__long_malloc_use_02_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_12_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_08_good();

	void CWE758_Undefined_Behavior__long_alloca_use_05_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_11_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_13_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_13_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_04_good();

	void CWE758_Undefined_Behavior__int_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_08_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_08_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_01_good();

	void CWE758_Undefined_Behavior__int_alloca_use_12_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_16_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_03_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_17_good();

	void CWE758_Undefined_Behavior__int_malloc_use_03_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_15_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_09_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_17_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_16_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_09_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_13_good();

	void CWE758_Undefined_Behavior__long_alloca_use_09_good();

	void CWE758_Undefined_Behavior__char_malloc_use_14_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_08_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_08_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_06_good();

	void CWE758_Undefined_Behavior__long_alloca_use_11_good();

	void CWE758_Undefined_Behavior__char_malloc_use_13_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_15_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_15_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_17_good();

	void CWE758_Undefined_Behavior__int_alloca_use_15_good();

	void CWE758_Undefined_Behavior__char_malloc_use_09_good();

	void CWE758_Undefined_Behavior__char_alloca_use_10_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_12_good();

	void CWE758_Undefined_Behavior__long_malloc_use_04_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_06_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_11_good();

	void CWE758_Undefined_Behavior__int_alloca_use_10_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_09_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_11_good();

	void CWE758_Undefined_Behavior__int_malloc_use_04_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_11_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_15_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_08_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_13_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_01_good();

	void CWE758_Undefined_Behavior__int_malloc_use_01_good();

	void CWE758_Undefined_Behavior__char_alloca_use_01_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_06_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_01_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_17_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_14_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_11_good();

	void CWE758_Undefined_Behavior__int_malloc_use_16_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_02_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_03_good();

	void CWE758_Undefined_Behavior__char_malloc_use_12_good();

	void CWE758_Undefined_Behavior__char_alloca_use_04_good();

	void CWE758_Undefined_Behavior__long_malloc_use_11_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_18_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_02_good();

	void CWE758_Undefined_Behavior__w32_bare_return_implicit_01_good();

	void CWE758_Undefined_Behavior__char_alloca_use_12_good();

	void CWE758_Undefined_Behavior__w32_no_return_implicit_01_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_16_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_16_good();

	void CWE758_Undefined_Behavior__long_alloca_use_14_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_04_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_10_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_09_good();

	void CWE758_Undefined_Behavior__long_malloc_use_05_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_17_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_15_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_04_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_12_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_02_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_07_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_02_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_01_good();

	void CWE758_Undefined_Behavior__int_malloc_use_12_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_10_good();

	void CWE758_Undefined_Behavior__int_malloc_use_06_good();

	void CWE758_Undefined_Behavior__long_alloca_use_06_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_13_good();

	void CWE758_Undefined_Behavior__char_alloca_use_06_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_07_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_03_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_08_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_05_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_07_good();

	void CWE758_Undefined_Behavior__long_malloc_use_03_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_03_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_12_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_06_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_18_good();

	void CWE758_Undefined_Behavior__long_alloca_use_16_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_08_good();

	void CWE758_Undefined_Behavior__int_malloc_use_11_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_10_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_05_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_18_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_03_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_17_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_07_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_11_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_11_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_16_good();

	void CWE758_Undefined_Behavior__char_alloca_use_07_good();

	void CWE758_Undefined_Behavior__char_malloc_use_10_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_01_good();

	void CWE758_Undefined_Behavior__char_malloc_use_15_good();

	void CWE758_Undefined_Behavior__char_malloc_use_08_good();

	void CWE758_Undefined_Behavior__char_malloc_use_01_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_08_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_04_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_12_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_02_good();

	void CWE758_Undefined_Behavior__char_malloc_use_18_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_04_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_16_good();

	void CWE758_Undefined_Behavior__long_alloca_use_03_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_12_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_01_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_16_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_04_good();

	void CWE758_Undefined_Behavior__long_alloca_use_04_good();

	void CWE758_Undefined_Behavior__char_malloc_use_06_good();

	void CWE758_Undefined_Behavior__int_malloc_use_15_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_14_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_08_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_01_good();

	void CWE758_Undefined_Behavior__char_alloca_use_11_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_11_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_02_good();

	void CWE758_Undefined_Behavior__long_malloc_use_16_good();

	void CWE758_Undefined_Behavior__int_malloc_use_09_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_01_good();

	void CWE758_Undefined_Behavior__char_malloc_use_04_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_06_good();

	void CWE758_Undefined_Behavior__int_alloca_use_09_good();

	void CWE758_Undefined_Behavior__long_alloca_use_17_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_10_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_16_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_04_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_01_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_18_good();

	void CWE758_Undefined_Behavior__char_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_05_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_06_good();

	void CWE758_Undefined_Behavior__long_malloc_use_09_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_09_good();

	void CWE758_Undefined_Behavior__char_alloca_use_05_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_04_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_13_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_10_good();

	void CWE758_Undefined_Behavior__int_alloca_use_04_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_17_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_12_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_03_good();

	void CWE758_Undefined_Behavior__long_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_07_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_16_good();

	void CWE758_Undefined_Behavior__long_alloca_use_07_good();

	void CWE758_Undefined_Behavior__long_malloc_use_10_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_03_good();

	void CWE758_Undefined_Behavior__char_alloca_use_02_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_10_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_05_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_13_good();

	void CWE758_Undefined_Behavior__int_alloca_use_06_good();

	void CWE758_Undefined_Behavior__char_malloc_use_17_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_09_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_11_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_11_good();

	void CWE758_Undefined_Behavior__long_alloca_use_12_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_06_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_14_good();

	void CWE758_Undefined_Behavior__char_alloca_use_09_good();

	void CWE758_Undefined_Behavior__int_alloca_use_13_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_17_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_13_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_15_good();

	void CWE758_Undefined_Behavior__int_alloca_use_17_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_02_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_15_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_05_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_14_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_15_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_17_good();

	void CWE758_Undefined_Behavior__long_malloc_use_06_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_02_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_06_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_01_good();

	void CWE758_Undefined_Behavior__int_alloca_use_08_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_15_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_08_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_12_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_13_good();

	void CWE758_Undefined_Behavior__char_malloc_use_07_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_04_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_03_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_06_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_17_good();

	void CWE758_Undefined_Behavior__long_alloca_use_10_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_16_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_01_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_14_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_02_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_05_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_11_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_09_good();

	void CWE758_Undefined_Behavior__int_malloc_use_05_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_03_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_12_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_05_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_15_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_02_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_09_good();

	void CWE758_Undefined_Behavior__long_malloc_use_12_good();

	void CWE758_Undefined_Behavior__long_malloc_use_08_good();

	void CWE758_Undefined_Behavior__long_alloca_use_15_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_17_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_01_good();

	void CWE758_Undefined_Behavior__int_malloc_use_17_good();

	void CWE758_Undefined_Behavior__char_malloc_use_11_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_07_good();

	void CWE758_Undefined_Behavior__w32_bare_return_01_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_13_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_08_good();

	void CWE758_Undefined_Behavior__int_malloc_use_13_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_08_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_17_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_13_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_04_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_18_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_14_good();

	void CWE758_Undefined_Behavior__long_alloca_use_08_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_06_good();

	void CWE758_Undefined_Behavior__int_alloca_use_05_good();

	void CWE758_Undefined_Behavior__int_malloc_use_10_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_11_good();

	void CWE758_Undefined_Behavior__char_alloca_use_13_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_04_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_07_good();

	void CWE758_Undefined_Behavior__char_alloca_use_15_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_16_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_03_good();

	void CWE758_Undefined_Behavior__long_alloca_use_13_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_02_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_13_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_05_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_14_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_08_good();

	void CWE758_Undefined_Behavior__int_malloc_use_14_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_03_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_10_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_05_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_18_good();

	void CWE758_Undefined_Behavior__int_malloc_use_02_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_05_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_14_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_02_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_06_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_07_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_09_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_02_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_15_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_12_good();

	void CWE758_Undefined_Behavior__long_alloca_use_02_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_05_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_07_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_10_good();

	void CWE758_Undefined_Behavior__int_alloca_use_01_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_14_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_18_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_10_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_07_good();

	void CWE758_Undefined_Behavior__char_alloca_use_03_good();

	void CWE758_Undefined_Behavior__long_malloc_use_14_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_04_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_14_good();

	void CWE758_Undefined_Behavior__char_malloc_use_03_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_18_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_11_good();

	void CWE758_Undefined_Behavior__long_malloc_use_17_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_14_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_15_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_13_good();

	void CWE758_Undefined_Behavior__int_alloca_use_11_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_06_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_06_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_04_good();

	void CWE758_Undefined_Behavior__long_malloc_use_18_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_07_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_07_good();

	void CWE758_Undefined_Behavior__int_malloc_use_08_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_10_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_09_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_12_good();

	void CWE758_Undefined_Behavior__int_alloca_use_14_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_07_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_05_good();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_17_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_15_good();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_09_good();

	void CWE758_Undefined_Behavior__char_alloca_use_17_good();

	void CWE758_Undefined_Behavior__no_return_01_good();

	void CWE758_Undefined_Behavior__long_malloc_use_01_good();

	void CWE758_Undefined_Behavior__int_alloca_use_07_good();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_12_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_03_good();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_01_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_16_good();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_15_good();

	void CWE758_Undefined_Behavior__int_malloc_use_07_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_14_good();

	void CWE758_Undefined_Behavior__char_malloc_use_02_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_02_good();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_09_good();

	void CWE758_Undefined_Behavior__struct_malloc_use_05_good();

	void CWE758_Undefined_Behavior__int_alloca_use_02_good();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_10_good();

	void CWE758_Undefined_Behavior__char_alloca_use_16_good();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_17_good();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_12_good();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_12_good();

	void CWE758_Undefined_Behavior__long_malloc_use_15_good();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_10_good();

	void CWE758_Undefined_Behavior__struct_alloca_use_09_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE758_Undefined_Behavior__char_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__w32_return_implicit_01_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__w32_bare_return_implicit_01_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__w32_no_return_implicit_01_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__w32_bare_return_01_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_11_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_04_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_13_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_08_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_06_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__long_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_01_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_14_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_03_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_18_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_15_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_13_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_11_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_06_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_04_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_18_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_08_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_09_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_05_bad();

	void CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__int_pointer_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_17_bad();

	void CWE758_Undefined_Behavior__no_return_01_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_07_bad();

	void CWE758_Undefined_Behavior__double_pointer_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_03_bad();

	void CWE758_Undefined_Behavior__int_pointer_malloc_use_01_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_16_bad();

	void CWE758_Undefined_Behavior__char_pointer_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__int_malloc_use_07_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_14_bad();

	void CWE758_Undefined_Behavior__char_malloc_use_02_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__char_pointer_alloca_use_09_bad();

	void CWE758_Undefined_Behavior__struct_malloc_use_05_bad();

	void CWE758_Undefined_Behavior__int_alloca_use_02_bad();

	void CWE758_Undefined_Behavior__struct_pointer_malloc_use_10_bad();

	void CWE758_Undefined_Behavior__char_alloca_use_16_bad();

	void CWE758_Undefined_Behavior__int64_t_malloc_use_17_bad();

	void CWE758_Undefined_Behavior__double_pointer_malloc_use_12_bad();

	void CWE758_Undefined_Behavior__struct_pointer_alloca_use_12_bad();

	void CWE758_Undefined_Behavior__long_malloc_use_15_bad();

	void CWE758_Undefined_Behavior__int64_t_alloca_use_10_bad();

	void CWE758_Undefined_Behavior__struct_alloca_use_09_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
