// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_64_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_05_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_10_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_11_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_12_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_51_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_66_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_63_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_17_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_63_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_08_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_54_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_31_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_18_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_03_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_10_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_32_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_16_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_16_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_64_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_68_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_65_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_13_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_06_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_07_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_03_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_02_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_65_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_14_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_52_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_14_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_04_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_41_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_52_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_53_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_15_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_34_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_54_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_01_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_67_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_18_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_15_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_53_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_17_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_51_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_45_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_02_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_34_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_09_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_04_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_44_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_41_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_12_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_45_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_09_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_08_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_44_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_07_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_66_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_06_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_05_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_32_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_13_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_01_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_67_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_11_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_68_good();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_31_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_64_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_05_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_10_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_11_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_12_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_51_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_66_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_63_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_17_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_63_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_08_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_54_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_31_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_18_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_03_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_10_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_32_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_16_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_16_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_64_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_68_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_65_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_13_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_06_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_07_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_03_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_02_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_65_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_14_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_52_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_14_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_04_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_41_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_52_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_53_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_15_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_34_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_54_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_01_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_67_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_18_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_15_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_53_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_17_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_51_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_45_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_02_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_34_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_09_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_04_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_44_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_41_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_12_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_45_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_09_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_08_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_44_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_07_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_66_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_06_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_05_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_32_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_13_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_01_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_67_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_11_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_loop_68_bad();

	void CWE124_Buffer_Underwrite__wchar_t_alloca_cpy_31_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
