/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_45_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_45_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_07_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_07_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_10_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_10_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_08_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_08_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_13_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_13_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_53_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_53_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_14_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_14_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_53_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_53_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_15_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_15_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_02_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_02_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_52_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_52_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_14_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_14_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_14_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_14_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_06_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_06_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_32_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_32_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_31_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_31_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_31_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_31_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_06_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_06_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_18_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_18_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_17_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_17_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_10_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_10_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_63_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_63_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_07_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_07_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_11_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_11_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_13_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_13_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_52_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_52_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_14_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_14_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_16_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_16_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_64_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_64_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_64_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_64_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_01_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_01_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_14_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_14_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_08_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_08_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_18_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_18_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_03_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_03_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_53_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_53_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_13_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_13_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_15_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_15_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_01_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_01_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_04_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_04_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_09_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_09_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_10_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_10_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_11_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_11_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_67_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_67_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_03_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_03_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_65_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_65_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_45_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_45_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_06_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_06_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_01_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_01_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_52_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_52_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_68_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_68_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_08_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_08_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_66_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_66_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_07_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_07_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_41_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_41_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_63_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_63_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_45_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_45_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_15_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_15_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_67_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_67_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_11_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_11_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_64_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_64_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_51_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_51_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_09_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_09_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_16_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_16_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_17_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_17_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_02_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_02_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_09_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_09_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_09_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_09_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_45_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_45_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_54_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_54_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_63_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_63_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_63_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_63_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_67_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_67_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_12_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_12_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_11_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_11_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_54_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_54_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_17_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_17_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_04_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_04_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_09_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_09_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_04_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_04_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_15_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_15_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_15_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_15_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_07_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_07_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_13_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_13_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_14_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_14_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_54_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_54_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_17_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_17_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_66_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_66_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_64_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_64_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_52_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_52_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_34_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_34_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_08_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_08_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_41_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_41_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_18_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_18_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_16_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_16_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_45_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_45_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_41_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_41_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_32_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_32_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_32_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_32_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_51_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_51_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_08_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_08_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_31_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_31_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_03_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_03_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_68_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_68_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_52_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_52_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_51_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_51_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_31_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_31_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_65_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_65_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_63_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_63_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_12_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_12_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_11_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_11_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_05_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_05_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_67_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_67_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_05_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_05_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_53_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_53_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_03_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_03_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_15_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_15_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_52_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_52_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_68_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_68_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_31_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_31_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_02_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_02_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_51_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_51_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_34_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_34_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_04_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_04_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_65_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_65_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_68_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_68_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_03_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_03_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_10_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_10_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_66_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_66_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_06_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_06_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_66_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_66_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_02_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_02_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_44_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_44_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_64_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_64_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_05_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_05_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_67_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_67_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_11_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_11_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_54_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_54_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_16_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_16_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_10_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_10_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_63_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_63_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_06_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_06_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_65_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_65_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_44_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_44_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_02_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_02_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_31_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_31_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_10_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_10_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_01_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_01_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_13_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_13_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_12_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_12_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_32_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_32_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_07_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_07_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_17_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_17_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_17_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_17_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_16_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_16_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_12_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_12_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_34_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_34_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_66_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_66_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_16_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_16_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_02_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_02_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_18_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_18_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_41_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_41_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_65_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_65_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_53_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_53_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_54_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_54_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_44_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_44_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_45_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_45_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_08_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_08_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_06_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_06_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_03_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_03_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_18_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_18_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_32_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_32_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_18_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_18_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_51_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_51_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_67_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_67_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_68_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_68_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_34_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_34_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_05_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_05_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_05_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_05_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_66_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_66_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_54_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_54_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_53_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_53_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_12_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_12_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_04_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_04_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_44_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_44_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_09_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_09_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_44_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_44_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_44_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_44_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_34_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_34_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_34_good();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_34_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_68_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_68_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_51_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_51_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_04_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_04_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_12_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_12_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_01_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_01_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_41_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_41_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_05_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_05_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_41_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_41_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_32_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_32_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_07_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_07_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_01_good();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_01_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_13_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_13_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_64_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_64_good();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_65_good();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_65_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_45_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_45_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_07_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_07_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_10_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_10_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_08_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_08_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_13_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_13_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_53_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_53_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_14_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_14_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_53_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_53_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_15_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_15_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_02_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_02_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_52_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_52_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_14_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_14_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_14_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_14_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_06_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_06_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_32_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_32_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_31_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_31_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_31_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_31_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_06_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_06_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_18_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_18_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_17_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_17_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_10_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_10_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_63_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_63_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_07_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_07_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_11_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_11_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_13_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_13_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_52_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_52_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_14_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_14_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_16_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_16_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_64_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_64_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_64_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_64_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_01_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_01_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_14_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_14_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_08_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_08_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_18_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_18_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_03_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_03_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_53_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_53_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_13_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_13_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_15_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_15_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_01_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_01_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_04_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_04_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_09_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_09_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_10_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_10_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_11_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_11_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_67_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_67_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_03_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_03_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_65_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_65_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_45_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_45_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_06_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_06_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_01_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_01_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_52_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_52_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_68_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_68_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_08_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_08_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_66_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_66_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_07_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_07_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_41_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_41_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_63_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_63_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_45_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_45_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_15_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_15_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_67_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_67_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_11_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_11_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_64_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_64_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_51_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_51_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_09_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_09_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_16_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_16_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_17_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_17_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_02_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_02_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_09_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_09_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_09_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_09_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_45_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_45_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_54_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_54_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_63_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_63_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_63_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_63_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_67_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_67_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_12_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_12_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_11_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_11_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_54_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_54_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_17_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_17_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_04_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_04_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_09_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_09_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_04_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_04_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_15_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_15_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_15_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_15_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_07_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_07_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_13_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_13_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_14_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_14_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_54_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_54_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_17_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_17_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_66_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_66_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_64_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_64_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_52_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_52_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_34_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_34_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_08_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_08_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_41_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_41_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_18_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_18_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_16_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_16_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_45_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_45_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_41_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_41_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_32_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_32_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_32_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_32_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_51_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_51_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_08_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_08_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_31_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_31_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_03_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_03_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_68_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_68_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_52_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_52_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_51_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_51_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_31_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_31_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_65_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_65_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_63_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_63_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_12_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_12_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_11_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_11_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_05_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_05_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_67_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_67_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_05_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_05_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_53_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_53_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_03_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_03_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_15_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_15_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_52_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_52_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_68_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_68_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_31_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_31_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_02_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_02_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_51_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_51_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_34_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_34_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_04_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_04_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_65_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_65_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_68_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_68_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_03_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_03_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_10_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_10_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_66_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_66_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_06_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_06_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_66_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_66_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_02_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_02_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_44_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_44_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_64_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_64_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_05_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_05_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_67_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_67_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_11_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_11_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_54_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_54_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_16_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_16_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_10_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_10_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_63_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_63_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_06_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_06_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_65_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_65_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_44_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_44_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_02_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_02_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_31_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_31_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_10_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_10_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_01_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_01_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_13_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_13_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_12_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_12_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_32_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_32_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_07_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_07_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_17_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_17_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_17_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_17_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_16_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_16_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_12_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_12_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_34_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_34_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_66_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_66_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_16_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_16_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_02_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_02_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_18_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_18_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_41_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_41_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_65_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_65_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_53_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_53_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_54_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_54_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_44_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_44_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_45_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_45_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_08_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_08_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_06_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_06_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_03_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_03_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_18_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_18_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_32_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_32_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_18_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_18_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_51_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_51_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_67_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_67_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_68_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_68_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_34_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_34_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_05_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_05_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_05_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_05_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_66_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_66_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_54_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_54_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_53_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_53_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_12_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_12_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_04_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_04_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_44_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_44_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_09_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_09_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_44_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_44_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_44_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_44_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_34_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_34_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_loop_34_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_loop_34_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_68_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_68_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_51_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_51_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_04_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_04_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_12_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_12_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_01_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_01_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memcpy_41_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memcpy_41_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_05_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_05_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_41_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_41_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memmove_32_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memmove_32_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_07_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_07_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_declare_memcpy_01_bad();");
	CWE126_Buffer_Overread__wchar_t_declare_memcpy_01_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_13_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_13_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_memmove_64_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_memmove_64_bad();

	printLine("Calling CWE126_Buffer_Overread__wchar_t_alloca_loop_65_bad();");
	CWE126_Buffer_Overread__wchar_t_alloca_loop_65_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
