/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE415_Double_Free__malloc_free_struct_61_good();");
	CWE415_Double_Free__malloc_free_struct_61_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_15_good();");
	CWE415_Double_Free__malloc_free_int64_t_15_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_13_good();");
	CWE415_Double_Free__malloc_free_int64_t_13_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_64_good();");
	CWE415_Double_Free__malloc_free_long_64_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_10_good();");
	CWE415_Double_Free__malloc_free_struct_10_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_63_good();");
	CWE415_Double_Free__malloc_free_int_63_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_02_good();");
	CWE415_Double_Free__malloc_free_int_02_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_12_good();");
	CWE415_Double_Free__malloc_free_struct_12_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_22_good();");
	CWE415_Double_Free__malloc_free_struct_22_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_10_good();");
	CWE415_Double_Free__malloc_free_int_10_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_42_good();");
	CWE415_Double_Free__malloc_free_wchar_t_42_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_17_good();");
	CWE415_Double_Free__malloc_free_char_17_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_09_good();");
	CWE415_Double_Free__malloc_free_long_09_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_53_good();");
	CWE415_Double_Free__malloc_free_long_53_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_32_good();");
	CWE415_Double_Free__malloc_free_int_32_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_17_good();");
	CWE415_Double_Free__malloc_free_int_17_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_64_good();");
	CWE415_Double_Free__malloc_free_int_64_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_54_good();");
	CWE415_Double_Free__malloc_free_int_54_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_16_good();");
	CWE415_Double_Free__malloc_free_wchar_t_16_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_42_good();");
	CWE415_Double_Free__malloc_free_long_42_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_22_good();");
	CWE415_Double_Free__malloc_free_int64_t_22_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_21_good();");
	CWE415_Double_Free__malloc_free_wchar_t_21_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_17_good();");
	CWE415_Double_Free__malloc_free_struct_17_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_61_good();");
	CWE415_Double_Free__malloc_free_wchar_t_61_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_65_good();");
	CWE415_Double_Free__malloc_free_struct_65_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_41_good();");
	CWE415_Double_Free__malloc_free_int_41_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_15_good();");
	CWE415_Double_Free__malloc_free_long_15_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_15_good();");
	CWE415_Double_Free__malloc_free_struct_15_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_41_good();");
	CWE415_Double_Free__malloc_free_char_41_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_17_good();");
	CWE415_Double_Free__malloc_free_long_17_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_12_good();");
	CWE415_Double_Free__malloc_free_wchar_t_12_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_31_good();");
	CWE415_Double_Free__malloc_free_int64_t_31_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_07_good();");
	CWE415_Double_Free__malloc_free_int64_t_07_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_12_good();");
	CWE415_Double_Free__malloc_free_long_12_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_03_good();");
	CWE415_Double_Free__malloc_free_wchar_t_03_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_67_good();");
	CWE415_Double_Free__malloc_free_int_67_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_03_good();");
	CWE415_Double_Free__malloc_free_char_03_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_66_good();");
	CWE415_Double_Free__malloc_free_struct_66_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_12_good();");
	CWE415_Double_Free__malloc_free_int_12_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_06_good();");
	CWE415_Double_Free__malloc_free_char_06_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_52_good();");
	CWE415_Double_Free__malloc_free_struct_52_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_13_good();");
	CWE415_Double_Free__malloc_free_int_13_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_08_good();");
	CWE415_Double_Free__malloc_free_wchar_t_08_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_12_good();");
	CWE415_Double_Free__malloc_free_int64_t_12_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_53_good();");
	CWE415_Double_Free__malloc_free_char_53_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_06_good();");
	CWE415_Double_Free__malloc_free_int_06_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_16_good();");
	CWE415_Double_Free__malloc_free_struct_16_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_22_good();");
	CWE415_Double_Free__malloc_free_wchar_t_22_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_21_good();");
	CWE415_Double_Free__malloc_free_int_21_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_04_good();");
	CWE415_Double_Free__malloc_free_wchar_t_04_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_34_good();");
	CWE415_Double_Free__malloc_free_char_34_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_09_good();");
	CWE415_Double_Free__malloc_free_wchar_t_09_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_04_good();");
	CWE415_Double_Free__malloc_free_struct_04_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_05_good();");
	CWE415_Double_Free__malloc_free_char_05_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_18_good();");
	CWE415_Double_Free__malloc_free_int64_t_18_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_07_good();");
	CWE415_Double_Free__malloc_free_char_07_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_02_good();");
	CWE415_Double_Free__malloc_free_wchar_t_02_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_09_good();");
	CWE415_Double_Free__malloc_free_int64_t_09_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_07_good();");
	CWE415_Double_Free__malloc_free_int_07_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_52_good();");
	CWE415_Double_Free__malloc_free_int64_t_52_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_44_good();");
	CWE415_Double_Free__malloc_free_wchar_t_44_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_07_good();");
	CWE415_Double_Free__malloc_free_struct_07_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_11_good();");
	CWE415_Double_Free__malloc_free_long_11_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_34_good();");
	CWE415_Double_Free__malloc_free_wchar_t_34_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_68_good();");
	CWE415_Double_Free__malloc_free_int_68_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_44_good();");
	CWE415_Double_Free__malloc_free_long_44_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_10_good();");
	CWE415_Double_Free__malloc_free_long_10_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_44_good();");
	CWE415_Double_Free__malloc_free_int64_t_44_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_64_good();");
	CWE415_Double_Free__malloc_free_int64_t_64_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_05_good();");
	CWE415_Double_Free__malloc_free_int_05_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_67_good();");
	CWE415_Double_Free__malloc_free_long_67_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_34_good();");
	CWE415_Double_Free__malloc_free_long_34_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_03_good();");
	CWE415_Double_Free__malloc_free_struct_03_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_13_good();");
	CWE415_Double_Free__malloc_free_char_13_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_31_good();");
	CWE415_Double_Free__malloc_free_int_31_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_34_good();");
	CWE415_Double_Free__malloc_free_struct_34_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_15_good();");
	CWE415_Double_Free__malloc_free_char_15_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_44_good();");
	CWE415_Double_Free__malloc_free_char_44_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_66_good();");
	CWE415_Double_Free__malloc_free_int64_t_66_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_16_good();");
	CWE415_Double_Free__malloc_free_int64_t_16_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_09_good();");
	CWE415_Double_Free__malloc_free_char_09_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_51_good();");
	CWE415_Double_Free__malloc_free_long_51_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_63_good();");
	CWE415_Double_Free__malloc_free_char_63_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_14_good();");
	CWE415_Double_Free__malloc_free_struct_14_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_02_good();");
	CWE415_Double_Free__malloc_free_int64_t_02_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_03_good();");
	CWE415_Double_Free__malloc_free_int64_t_03_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_64_good();");
	CWE415_Double_Free__malloc_free_struct_64_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_53_good();");
	CWE415_Double_Free__malloc_free_struct_53_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_42_good();");
	CWE415_Double_Free__malloc_free_struct_42_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_42_good();");
	CWE415_Double_Free__malloc_free_int_42_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_68_good();");
	CWE415_Double_Free__malloc_free_char_68_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_08_good();");
	CWE415_Double_Free__malloc_free_int64_t_08_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_21_good();");
	CWE415_Double_Free__malloc_free_long_21_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_08_good();");
	CWE415_Double_Free__malloc_free_long_08_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_53_good();");
	CWE415_Double_Free__malloc_free_int_53_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_53_good();");
	CWE415_Double_Free__malloc_free_int64_t_53_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_45_good();");
	CWE415_Double_Free__malloc_free_struct_45_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_22_good();");
	CWE415_Double_Free__malloc_free_int_22_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_32_good();");
	CWE415_Double_Free__malloc_free_struct_32_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_61_good();");
	CWE415_Double_Free__malloc_free_int_61_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_11_good();");
	CWE415_Double_Free__malloc_free_int_11_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_66_good();");
	CWE415_Double_Free__malloc_free_long_66_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_34_good();");
	CWE415_Double_Free__malloc_free_int64_t_34_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_13_good();");
	CWE415_Double_Free__malloc_free_wchar_t_13_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_17_good();");
	CWE415_Double_Free__malloc_free_int64_t_17_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_18_good();");
	CWE415_Double_Free__malloc_free_char_18_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_53_good();");
	CWE415_Double_Free__malloc_free_wchar_t_53_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_54_good();");
	CWE415_Double_Free__malloc_free_wchar_t_54_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_04_good();");
	CWE415_Double_Free__malloc_free_long_04_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_63_good();");
	CWE415_Double_Free__malloc_free_long_63_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_01_good();");
	CWE415_Double_Free__malloc_free_char_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_42_good();");
	CWE415_Double_Free__malloc_free_char_42_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_02_good();");
	CWE415_Double_Free__malloc_free_struct_02_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_31_good();");
	CWE415_Double_Free__malloc_free_char_31_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_44_good();");
	CWE415_Double_Free__malloc_free_struct_44_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_18_good();");
	CWE415_Double_Free__malloc_free_int_18_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_02_good();");
	CWE415_Double_Free__malloc_free_long_02_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_51_good();");
	CWE415_Double_Free__malloc_free_struct_51_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_03_good();");
	CWE415_Double_Free__malloc_free_int_03_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_51_good();");
	CWE415_Double_Free__malloc_free_wchar_t_51_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_11_good();");
	CWE415_Double_Free__malloc_free_int64_t_11_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_65_good();");
	CWE415_Double_Free__malloc_free_long_65_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_01_good();");
	CWE415_Double_Free__malloc_free_long_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_21_good();");
	CWE415_Double_Free__malloc_free_char_21_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_14_good();");
	CWE415_Double_Free__malloc_free_long_14_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_01_good();");
	CWE415_Double_Free__malloc_free_int64_t_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_54_good();");
	CWE415_Double_Free__malloc_free_long_54_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_09_good();");
	CWE415_Double_Free__malloc_free_struct_09_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_31_good();");
	CWE415_Double_Free__malloc_free_struct_31_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_05_good();");
	CWE415_Double_Free__malloc_free_long_05_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_65_good();");
	CWE415_Double_Free__malloc_free_int_65_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_21_good();");
	CWE415_Double_Free__malloc_free_int64_t_21_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_21_good();");
	CWE415_Double_Free__malloc_free_struct_21_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_31_good();");
	CWE415_Double_Free__malloc_free_wchar_t_31_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_10_good();");
	CWE415_Double_Free__malloc_free_int64_t_10_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_68_good();");
	CWE415_Double_Free__malloc_free_long_68_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_54_good();");
	CWE415_Double_Free__malloc_free_char_54_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_01_good();");
	CWE415_Double_Free__malloc_free_wchar_t_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_07_good();");
	CWE415_Double_Free__malloc_free_wchar_t_07_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_64_good();");
	CWE415_Double_Free__malloc_free_wchar_t_64_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_45_good();");
	CWE415_Double_Free__malloc_free_wchar_t_45_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_64_good();");
	CWE415_Double_Free__malloc_free_char_64_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_32_good();");
	CWE415_Double_Free__malloc_free_wchar_t_32_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_17_good();");
	CWE415_Double_Free__malloc_free_wchar_t_17_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_51_good();");
	CWE415_Double_Free__malloc_free_char_51_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_51_good();");
	CWE415_Double_Free__malloc_free_int_51_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_08_good();");
	CWE415_Double_Free__malloc_free_char_08_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_18_good();");
	CWE415_Double_Free__malloc_free_long_18_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_06_good();");
	CWE415_Double_Free__malloc_free_wchar_t_06_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_45_good();");
	CWE415_Double_Free__malloc_free_long_45_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_66_good();");
	CWE415_Double_Free__malloc_free_char_66_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_14_good();");
	CWE415_Double_Free__malloc_free_int64_t_14_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_67_good();");
	CWE415_Double_Free__malloc_free_wchar_t_67_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_51_good();");
	CWE415_Double_Free__malloc_free_int64_t_51_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_61_good();");
	CWE415_Double_Free__malloc_free_long_61_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_10_good();");
	CWE415_Double_Free__malloc_free_wchar_t_10_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_67_good();");
	CWE415_Double_Free__malloc_free_char_67_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_41_good();");
	CWE415_Double_Free__malloc_free_struct_41_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_18_good();");
	CWE415_Double_Free__malloc_free_wchar_t_18_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_54_good();");
	CWE415_Double_Free__malloc_free_struct_54_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_41_good();");
	CWE415_Double_Free__malloc_free_wchar_t_41_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_52_good();");
	CWE415_Double_Free__malloc_free_long_52_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_45_good();");
	CWE415_Double_Free__malloc_free_char_45_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_31_good();");
	CWE415_Double_Free__malloc_free_long_31_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_10_good();");
	CWE415_Double_Free__malloc_free_char_10_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_14_good();");
	CWE415_Double_Free__malloc_free_char_14_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_45_good();");
	CWE415_Double_Free__malloc_free_int64_t_45_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_63_good();");
	CWE415_Double_Free__malloc_free_wchar_t_63_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_68_good();");
	CWE415_Double_Free__malloc_free_struct_68_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_08_good();");
	CWE415_Double_Free__malloc_free_struct_08_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_61_good();");
	CWE415_Double_Free__malloc_free_char_61_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_13_good();");
	CWE415_Double_Free__malloc_free_struct_13_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_15_good();");
	CWE415_Double_Free__malloc_free_wchar_t_15_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_67_good();");
	CWE415_Double_Free__malloc_free_int64_t_67_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_04_good();");
	CWE415_Double_Free__malloc_free_char_04_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_61_good();");
	CWE415_Double_Free__malloc_free_int64_t_61_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_16_good();");
	CWE415_Double_Free__malloc_free_int_16_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_67_good();");
	CWE415_Double_Free__malloc_free_struct_67_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_34_good();");
	CWE415_Double_Free__malloc_free_int_34_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_06_good();");
	CWE415_Double_Free__malloc_free_long_06_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_07_good();");
	CWE415_Double_Free__malloc_free_long_07_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_09_good();");
	CWE415_Double_Free__malloc_free_int_09_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_44_good();");
	CWE415_Double_Free__malloc_free_int_44_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_04_good();");
	CWE415_Double_Free__malloc_free_int_04_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_52_good();");
	CWE415_Double_Free__malloc_free_char_52_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_45_good();");
	CWE415_Double_Free__malloc_free_int_45_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_54_good();");
	CWE415_Double_Free__malloc_free_int64_t_54_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_66_good();");
	CWE415_Double_Free__malloc_free_int_66_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_05_good();");
	CWE415_Double_Free__malloc_free_struct_05_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_66_good();");
	CWE415_Double_Free__malloc_free_wchar_t_66_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_02_good();");
	CWE415_Double_Free__malloc_free_char_02_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_41_good();");
	CWE415_Double_Free__malloc_free_int64_t_41_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_11_good();");
	CWE415_Double_Free__malloc_free_char_11_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_06_good();");
	CWE415_Double_Free__malloc_free_int64_t_06_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_13_good();");
	CWE415_Double_Free__malloc_free_long_13_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_14_good();");
	CWE415_Double_Free__malloc_free_wchar_t_14_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_68_good();");
	CWE415_Double_Free__malloc_free_wchar_t_68_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_15_good();");
	CWE415_Double_Free__malloc_free_int_15_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_65_good();");
	CWE415_Double_Free__malloc_free_int64_t_65_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_16_good();");
	CWE415_Double_Free__malloc_free_long_16_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_12_good();");
	CWE415_Double_Free__malloc_free_char_12_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_22_good();");
	CWE415_Double_Free__malloc_free_long_22_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_22_good();");
	CWE415_Double_Free__malloc_free_char_22_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_32_good();");
	CWE415_Double_Free__malloc_free_int64_t_32_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_05_good();");
	CWE415_Double_Free__malloc_free_int64_t_05_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_05_good();");
	CWE415_Double_Free__malloc_free_wchar_t_05_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_03_good();");
	CWE415_Double_Free__malloc_free_long_03_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_65_good();");
	CWE415_Double_Free__malloc_free_char_65_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_11_good();");
	CWE415_Double_Free__malloc_free_struct_11_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_01_good();");
	CWE415_Double_Free__malloc_free_struct_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_63_good();");
	CWE415_Double_Free__malloc_free_struct_63_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_08_good();");
	CWE415_Double_Free__malloc_free_int_08_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_42_good();");
	CWE415_Double_Free__malloc_free_int64_t_42_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_65_good();");
	CWE415_Double_Free__malloc_free_wchar_t_65_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_41_good();");
	CWE415_Double_Free__malloc_free_long_41_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_06_good();");
	CWE415_Double_Free__malloc_free_struct_06_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_01_good();");
	CWE415_Double_Free__malloc_free_int_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_32_good();");
	CWE415_Double_Free__malloc_free_char_32_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_63_good();");
	CWE415_Double_Free__malloc_free_int64_t_63_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_68_good();");
	CWE415_Double_Free__malloc_free_int64_t_68_good();

	printLine("Calling CWE415_Double_Free__malloc_free_long_32_good();");
	CWE415_Double_Free__malloc_free_long_32_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_04_good();");
	CWE415_Double_Free__malloc_free_int64_t_04_good();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_18_good();");
	CWE415_Double_Free__malloc_free_struct_18_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_52_good();");
	CWE415_Double_Free__malloc_free_int_52_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_16_good();");
	CWE415_Double_Free__malloc_free_char_16_good();

	printLine("Calling CWE415_Double_Free__malloc_free_int_14_good();");
	CWE415_Double_Free__malloc_free_int_14_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_52_good();");
	CWE415_Double_Free__malloc_free_wchar_t_52_good();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_11_good();");
	CWE415_Double_Free__malloc_free_wchar_t_11_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE415_Double_Free__malloc_free_struct_61_bad();");
	CWE415_Double_Free__malloc_free_struct_61_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_15_bad();");
	CWE415_Double_Free__malloc_free_int64_t_15_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_13_bad();");
	CWE415_Double_Free__malloc_free_int64_t_13_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_64_bad();");
	CWE415_Double_Free__malloc_free_long_64_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_10_bad();");
	CWE415_Double_Free__malloc_free_struct_10_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_63_bad();");
	CWE415_Double_Free__malloc_free_int_63_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_02_bad();");
	CWE415_Double_Free__malloc_free_int_02_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_12_bad();");
	CWE415_Double_Free__malloc_free_struct_12_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_22_bad();");
	CWE415_Double_Free__malloc_free_struct_22_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_10_bad();");
	CWE415_Double_Free__malloc_free_int_10_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_42_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_42_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_17_bad();");
	CWE415_Double_Free__malloc_free_char_17_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_09_bad();");
	CWE415_Double_Free__malloc_free_long_09_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_53_bad();");
	CWE415_Double_Free__malloc_free_long_53_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_32_bad();");
	CWE415_Double_Free__malloc_free_int_32_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_17_bad();");
	CWE415_Double_Free__malloc_free_int_17_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_64_bad();");
	CWE415_Double_Free__malloc_free_int_64_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_54_bad();");
	CWE415_Double_Free__malloc_free_int_54_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_16_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_16_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_42_bad();");
	CWE415_Double_Free__malloc_free_long_42_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_22_bad();");
	CWE415_Double_Free__malloc_free_int64_t_22_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_21_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_21_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_17_bad();");
	CWE415_Double_Free__malloc_free_struct_17_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_61_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_61_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_65_bad();");
	CWE415_Double_Free__malloc_free_struct_65_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_41_bad();");
	CWE415_Double_Free__malloc_free_int_41_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_15_bad();");
	CWE415_Double_Free__malloc_free_long_15_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_15_bad();");
	CWE415_Double_Free__malloc_free_struct_15_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_41_bad();");
	CWE415_Double_Free__malloc_free_char_41_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_17_bad();");
	CWE415_Double_Free__malloc_free_long_17_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_12_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_12_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_31_bad();");
	CWE415_Double_Free__malloc_free_int64_t_31_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_07_bad();");
	CWE415_Double_Free__malloc_free_int64_t_07_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_12_bad();");
	CWE415_Double_Free__malloc_free_long_12_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_03_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_03_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_67_bad();");
	CWE415_Double_Free__malloc_free_int_67_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_03_bad();");
	CWE415_Double_Free__malloc_free_char_03_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_66_bad();");
	CWE415_Double_Free__malloc_free_struct_66_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_12_bad();");
	CWE415_Double_Free__malloc_free_int_12_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_06_bad();");
	CWE415_Double_Free__malloc_free_char_06_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_52_bad();");
	CWE415_Double_Free__malloc_free_struct_52_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_13_bad();");
	CWE415_Double_Free__malloc_free_int_13_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_08_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_08_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_12_bad();");
	CWE415_Double_Free__malloc_free_int64_t_12_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_53_bad();");
	CWE415_Double_Free__malloc_free_char_53_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_06_bad();");
	CWE415_Double_Free__malloc_free_int_06_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_16_bad();");
	CWE415_Double_Free__malloc_free_struct_16_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_22_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_22_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_21_bad();");
	CWE415_Double_Free__malloc_free_int_21_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_04_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_04_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_34_bad();");
	CWE415_Double_Free__malloc_free_char_34_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_09_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_09_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_04_bad();");
	CWE415_Double_Free__malloc_free_struct_04_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_05_bad();");
	CWE415_Double_Free__malloc_free_char_05_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_18_bad();");
	CWE415_Double_Free__malloc_free_int64_t_18_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_07_bad();");
	CWE415_Double_Free__malloc_free_char_07_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_02_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_02_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_09_bad();");
	CWE415_Double_Free__malloc_free_int64_t_09_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_07_bad();");
	CWE415_Double_Free__malloc_free_int_07_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_52_bad();");
	CWE415_Double_Free__malloc_free_int64_t_52_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_44_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_44_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_07_bad();");
	CWE415_Double_Free__malloc_free_struct_07_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_11_bad();");
	CWE415_Double_Free__malloc_free_long_11_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_34_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_34_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_68_bad();");
	CWE415_Double_Free__malloc_free_int_68_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_44_bad();");
	CWE415_Double_Free__malloc_free_long_44_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_10_bad();");
	CWE415_Double_Free__malloc_free_long_10_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_44_bad();");
	CWE415_Double_Free__malloc_free_int64_t_44_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_64_bad();");
	CWE415_Double_Free__malloc_free_int64_t_64_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_05_bad();");
	CWE415_Double_Free__malloc_free_int_05_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_67_bad();");
	CWE415_Double_Free__malloc_free_long_67_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_34_bad();");
	CWE415_Double_Free__malloc_free_long_34_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_03_bad();");
	CWE415_Double_Free__malloc_free_struct_03_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_13_bad();");
	CWE415_Double_Free__malloc_free_char_13_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_31_bad();");
	CWE415_Double_Free__malloc_free_int_31_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_34_bad();");
	CWE415_Double_Free__malloc_free_struct_34_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_15_bad();");
	CWE415_Double_Free__malloc_free_char_15_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_44_bad();");
	CWE415_Double_Free__malloc_free_char_44_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_66_bad();");
	CWE415_Double_Free__malloc_free_int64_t_66_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_16_bad();");
	CWE415_Double_Free__malloc_free_int64_t_16_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_09_bad();");
	CWE415_Double_Free__malloc_free_char_09_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_51_bad();");
	CWE415_Double_Free__malloc_free_long_51_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_63_bad();");
	CWE415_Double_Free__malloc_free_char_63_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_14_bad();");
	CWE415_Double_Free__malloc_free_struct_14_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_02_bad();");
	CWE415_Double_Free__malloc_free_int64_t_02_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_03_bad();");
	CWE415_Double_Free__malloc_free_int64_t_03_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_64_bad();");
	CWE415_Double_Free__malloc_free_struct_64_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_53_bad();");
	CWE415_Double_Free__malloc_free_struct_53_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_42_bad();");
	CWE415_Double_Free__malloc_free_struct_42_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_42_bad();");
	CWE415_Double_Free__malloc_free_int_42_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_68_bad();");
	CWE415_Double_Free__malloc_free_char_68_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_08_bad();");
	CWE415_Double_Free__malloc_free_int64_t_08_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_21_bad();");
	CWE415_Double_Free__malloc_free_long_21_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_08_bad();");
	CWE415_Double_Free__malloc_free_long_08_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_53_bad();");
	CWE415_Double_Free__malloc_free_int_53_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_53_bad();");
	CWE415_Double_Free__malloc_free_int64_t_53_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_45_bad();");
	CWE415_Double_Free__malloc_free_struct_45_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_22_bad();");
	CWE415_Double_Free__malloc_free_int_22_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_32_bad();");
	CWE415_Double_Free__malloc_free_struct_32_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_61_bad();");
	CWE415_Double_Free__malloc_free_int_61_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_11_bad();");
	CWE415_Double_Free__malloc_free_int_11_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_66_bad();");
	CWE415_Double_Free__malloc_free_long_66_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_34_bad();");
	CWE415_Double_Free__malloc_free_int64_t_34_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_13_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_13_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_17_bad();");
	CWE415_Double_Free__malloc_free_int64_t_17_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_18_bad();");
	CWE415_Double_Free__malloc_free_char_18_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_53_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_53_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_54_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_54_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_04_bad();");
	CWE415_Double_Free__malloc_free_long_04_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_63_bad();");
	CWE415_Double_Free__malloc_free_long_63_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_01_bad();");
	CWE415_Double_Free__malloc_free_char_01_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_42_bad();");
	CWE415_Double_Free__malloc_free_char_42_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_02_bad();");
	CWE415_Double_Free__malloc_free_struct_02_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_31_bad();");
	CWE415_Double_Free__malloc_free_char_31_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_44_bad();");
	CWE415_Double_Free__malloc_free_struct_44_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_18_bad();");
	CWE415_Double_Free__malloc_free_int_18_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_02_bad();");
	CWE415_Double_Free__malloc_free_long_02_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_51_bad();");
	CWE415_Double_Free__malloc_free_struct_51_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_03_bad();");
	CWE415_Double_Free__malloc_free_int_03_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_51_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_51_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_11_bad();");
	CWE415_Double_Free__malloc_free_int64_t_11_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_65_bad();");
	CWE415_Double_Free__malloc_free_long_65_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_01_bad();");
	CWE415_Double_Free__malloc_free_long_01_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_21_bad();");
	CWE415_Double_Free__malloc_free_char_21_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_14_bad();");
	CWE415_Double_Free__malloc_free_long_14_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_01_bad();");
	CWE415_Double_Free__malloc_free_int64_t_01_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_54_bad();");
	CWE415_Double_Free__malloc_free_long_54_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_09_bad();");
	CWE415_Double_Free__malloc_free_struct_09_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_31_bad();");
	CWE415_Double_Free__malloc_free_struct_31_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_05_bad();");
	CWE415_Double_Free__malloc_free_long_05_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_65_bad();");
	CWE415_Double_Free__malloc_free_int_65_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_21_bad();");
	CWE415_Double_Free__malloc_free_int64_t_21_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_21_bad();");
	CWE415_Double_Free__malloc_free_struct_21_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_31_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_31_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_10_bad();");
	CWE415_Double_Free__malloc_free_int64_t_10_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_68_bad();");
	CWE415_Double_Free__malloc_free_long_68_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_54_bad();");
	CWE415_Double_Free__malloc_free_char_54_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_01_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_01_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_07_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_07_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_64_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_64_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_45_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_45_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_64_bad();");
	CWE415_Double_Free__malloc_free_char_64_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_32_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_32_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_17_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_17_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_51_bad();");
	CWE415_Double_Free__malloc_free_char_51_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_51_bad();");
	CWE415_Double_Free__malloc_free_int_51_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_08_bad();");
	CWE415_Double_Free__malloc_free_char_08_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_18_bad();");
	CWE415_Double_Free__malloc_free_long_18_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_06_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_06_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_45_bad();");
	CWE415_Double_Free__malloc_free_long_45_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_66_bad();");
	CWE415_Double_Free__malloc_free_char_66_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_14_bad();");
	CWE415_Double_Free__malloc_free_int64_t_14_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_67_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_67_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_51_bad();");
	CWE415_Double_Free__malloc_free_int64_t_51_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_61_bad();");
	CWE415_Double_Free__malloc_free_long_61_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_10_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_10_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_67_bad();");
	CWE415_Double_Free__malloc_free_char_67_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_41_bad();");
	CWE415_Double_Free__malloc_free_struct_41_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_18_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_18_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_54_bad();");
	CWE415_Double_Free__malloc_free_struct_54_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_41_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_41_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_52_bad();");
	CWE415_Double_Free__malloc_free_long_52_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_45_bad();");
	CWE415_Double_Free__malloc_free_char_45_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_31_bad();");
	CWE415_Double_Free__malloc_free_long_31_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_10_bad();");
	CWE415_Double_Free__malloc_free_char_10_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_14_bad();");
	CWE415_Double_Free__malloc_free_char_14_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_45_bad();");
	CWE415_Double_Free__malloc_free_int64_t_45_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_63_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_63_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_68_bad();");
	CWE415_Double_Free__malloc_free_struct_68_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_08_bad();");
	CWE415_Double_Free__malloc_free_struct_08_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_61_bad();");
	CWE415_Double_Free__malloc_free_char_61_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_13_bad();");
	CWE415_Double_Free__malloc_free_struct_13_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_15_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_15_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_67_bad();");
	CWE415_Double_Free__malloc_free_int64_t_67_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_04_bad();");
	CWE415_Double_Free__malloc_free_char_04_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_61_bad();");
	CWE415_Double_Free__malloc_free_int64_t_61_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_16_bad();");
	CWE415_Double_Free__malloc_free_int_16_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_67_bad();");
	CWE415_Double_Free__malloc_free_struct_67_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_34_bad();");
	CWE415_Double_Free__malloc_free_int_34_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_06_bad();");
	CWE415_Double_Free__malloc_free_long_06_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_07_bad();");
	CWE415_Double_Free__malloc_free_long_07_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_09_bad();");
	CWE415_Double_Free__malloc_free_int_09_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_44_bad();");
	CWE415_Double_Free__malloc_free_int_44_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_04_bad();");
	CWE415_Double_Free__malloc_free_int_04_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_52_bad();");
	CWE415_Double_Free__malloc_free_char_52_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_45_bad();");
	CWE415_Double_Free__malloc_free_int_45_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_54_bad();");
	CWE415_Double_Free__malloc_free_int64_t_54_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_66_bad();");
	CWE415_Double_Free__malloc_free_int_66_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_05_bad();");
	CWE415_Double_Free__malloc_free_struct_05_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_66_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_66_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_02_bad();");
	CWE415_Double_Free__malloc_free_char_02_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_41_bad();");
	CWE415_Double_Free__malloc_free_int64_t_41_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_11_bad();");
	CWE415_Double_Free__malloc_free_char_11_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_06_bad();");
	CWE415_Double_Free__malloc_free_int64_t_06_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_13_bad();");
	CWE415_Double_Free__malloc_free_long_13_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_14_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_14_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_68_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_68_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_15_bad();");
	CWE415_Double_Free__malloc_free_int_15_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_65_bad();");
	CWE415_Double_Free__malloc_free_int64_t_65_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_16_bad();");
	CWE415_Double_Free__malloc_free_long_16_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_12_bad();");
	CWE415_Double_Free__malloc_free_char_12_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_22_bad();");
	CWE415_Double_Free__malloc_free_long_22_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_22_bad();");
	CWE415_Double_Free__malloc_free_char_22_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_32_bad();");
	CWE415_Double_Free__malloc_free_int64_t_32_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_05_bad();");
	CWE415_Double_Free__malloc_free_int64_t_05_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_05_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_05_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_03_bad();");
	CWE415_Double_Free__malloc_free_long_03_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_65_bad();");
	CWE415_Double_Free__malloc_free_char_65_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_11_bad();");
	CWE415_Double_Free__malloc_free_struct_11_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_01_bad();");
	CWE415_Double_Free__malloc_free_struct_01_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_63_bad();");
	CWE415_Double_Free__malloc_free_struct_63_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_08_bad();");
	CWE415_Double_Free__malloc_free_int_08_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_42_bad();");
	CWE415_Double_Free__malloc_free_int64_t_42_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_65_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_65_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_41_bad();");
	CWE415_Double_Free__malloc_free_long_41_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_06_bad();");
	CWE415_Double_Free__malloc_free_struct_06_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_01_bad();");
	CWE415_Double_Free__malloc_free_int_01_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_32_bad();");
	CWE415_Double_Free__malloc_free_char_32_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_63_bad();");
	CWE415_Double_Free__malloc_free_int64_t_63_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_68_bad();");
	CWE415_Double_Free__malloc_free_int64_t_68_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_long_32_bad();");
	CWE415_Double_Free__malloc_free_long_32_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int64_t_04_bad();");
	CWE415_Double_Free__malloc_free_int64_t_04_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_struct_18_bad();");
	CWE415_Double_Free__malloc_free_struct_18_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_52_bad();");
	CWE415_Double_Free__malloc_free_int_52_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_char_16_bad();");
	CWE415_Double_Free__malloc_free_char_16_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_int_14_bad();");
	CWE415_Double_Free__malloc_free_int_14_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_52_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_52_bad();

	printLine("Calling CWE415_Double_Free__malloc_free_wchar_t_11_bad();");
	CWE415_Double_Free__malloc_free_wchar_t_11_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
