// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE415_Double_Free__malloc_free_struct_61_good();

	void CWE415_Double_Free__malloc_free_int64_t_15_good();

	void CWE415_Double_Free__malloc_free_int64_t_13_good();

	void CWE415_Double_Free__malloc_free_long_64_good();

	void CWE415_Double_Free__malloc_free_struct_10_good();

	void CWE415_Double_Free__malloc_free_int_63_good();

	void CWE415_Double_Free__malloc_free_int_02_good();

	void CWE415_Double_Free__malloc_free_struct_12_good();

	void CWE415_Double_Free__malloc_free_struct_22_good();

	void CWE415_Double_Free__malloc_free_int_10_good();

	void CWE415_Double_Free__malloc_free_wchar_t_42_good();

	void CWE415_Double_Free__malloc_free_char_17_good();

	void CWE415_Double_Free__malloc_free_long_09_good();

	void CWE415_Double_Free__malloc_free_long_53_good();

	void CWE415_Double_Free__malloc_free_int_32_good();

	void CWE415_Double_Free__malloc_free_int_17_good();

	void CWE415_Double_Free__malloc_free_int_64_good();

	void CWE415_Double_Free__malloc_free_int_54_good();

	void CWE415_Double_Free__malloc_free_wchar_t_16_good();

	void CWE415_Double_Free__malloc_free_long_42_good();

	void CWE415_Double_Free__malloc_free_int64_t_22_good();

	void CWE415_Double_Free__malloc_free_wchar_t_21_good();

	void CWE415_Double_Free__malloc_free_struct_17_good();

	void CWE415_Double_Free__malloc_free_wchar_t_61_good();

	void CWE415_Double_Free__malloc_free_struct_65_good();

	void CWE415_Double_Free__malloc_free_int_41_good();

	void CWE415_Double_Free__malloc_free_long_15_good();

	void CWE415_Double_Free__malloc_free_struct_15_good();

	void CWE415_Double_Free__malloc_free_char_41_good();

	void CWE415_Double_Free__malloc_free_long_17_good();

	void CWE415_Double_Free__malloc_free_wchar_t_12_good();

	void CWE415_Double_Free__malloc_free_int64_t_31_good();

	void CWE415_Double_Free__malloc_free_int64_t_07_good();

	void CWE415_Double_Free__malloc_free_long_12_good();

	void CWE415_Double_Free__malloc_free_wchar_t_03_good();

	void CWE415_Double_Free__malloc_free_int_67_good();

	void CWE415_Double_Free__malloc_free_char_03_good();

	void CWE415_Double_Free__malloc_free_struct_66_good();

	void CWE415_Double_Free__malloc_free_int_12_good();

	void CWE415_Double_Free__malloc_free_char_06_good();

	void CWE415_Double_Free__malloc_free_struct_52_good();

	void CWE415_Double_Free__malloc_free_int_13_good();

	void CWE415_Double_Free__malloc_free_wchar_t_08_good();

	void CWE415_Double_Free__malloc_free_int64_t_12_good();

	void CWE415_Double_Free__malloc_free_char_53_good();

	void CWE415_Double_Free__malloc_free_int_06_good();

	void CWE415_Double_Free__malloc_free_struct_16_good();

	void CWE415_Double_Free__malloc_free_wchar_t_22_good();

	void CWE415_Double_Free__malloc_free_int_21_good();

	void CWE415_Double_Free__malloc_free_wchar_t_04_good();

	void CWE415_Double_Free__malloc_free_char_34_good();

	void CWE415_Double_Free__malloc_free_wchar_t_09_good();

	void CWE415_Double_Free__malloc_free_struct_04_good();

	void CWE415_Double_Free__malloc_free_char_05_good();

	void CWE415_Double_Free__malloc_free_int64_t_18_good();

	void CWE415_Double_Free__malloc_free_char_07_good();

	void CWE415_Double_Free__malloc_free_wchar_t_02_good();

	void CWE415_Double_Free__malloc_free_int64_t_09_good();

	void CWE415_Double_Free__malloc_free_int_07_good();

	void CWE415_Double_Free__malloc_free_int64_t_52_good();

	void CWE415_Double_Free__malloc_free_wchar_t_44_good();

	void CWE415_Double_Free__malloc_free_struct_07_good();

	void CWE415_Double_Free__malloc_free_long_11_good();

	void CWE415_Double_Free__malloc_free_wchar_t_34_good();

	void CWE415_Double_Free__malloc_free_int_68_good();

	void CWE415_Double_Free__malloc_free_long_44_good();

	void CWE415_Double_Free__malloc_free_long_10_good();

	void CWE415_Double_Free__malloc_free_int64_t_44_good();

	void CWE415_Double_Free__malloc_free_int64_t_64_good();

	void CWE415_Double_Free__malloc_free_int_05_good();

	void CWE415_Double_Free__malloc_free_long_67_good();

	void CWE415_Double_Free__malloc_free_long_34_good();

	void CWE415_Double_Free__malloc_free_struct_03_good();

	void CWE415_Double_Free__malloc_free_char_13_good();

	void CWE415_Double_Free__malloc_free_int_31_good();

	void CWE415_Double_Free__malloc_free_struct_34_good();

	void CWE415_Double_Free__malloc_free_char_15_good();

	void CWE415_Double_Free__malloc_free_char_44_good();

	void CWE415_Double_Free__malloc_free_int64_t_66_good();

	void CWE415_Double_Free__malloc_free_int64_t_16_good();

	void CWE415_Double_Free__malloc_free_char_09_good();

	void CWE415_Double_Free__malloc_free_long_51_good();

	void CWE415_Double_Free__malloc_free_char_63_good();

	void CWE415_Double_Free__malloc_free_struct_14_good();

	void CWE415_Double_Free__malloc_free_int64_t_02_good();

	void CWE415_Double_Free__malloc_free_int64_t_03_good();

	void CWE415_Double_Free__malloc_free_struct_64_good();

	void CWE415_Double_Free__malloc_free_struct_53_good();

	void CWE415_Double_Free__malloc_free_struct_42_good();

	void CWE415_Double_Free__malloc_free_int_42_good();

	void CWE415_Double_Free__malloc_free_char_68_good();

	void CWE415_Double_Free__malloc_free_int64_t_08_good();

	void CWE415_Double_Free__malloc_free_long_21_good();

	void CWE415_Double_Free__malloc_free_long_08_good();

	void CWE415_Double_Free__malloc_free_int_53_good();

	void CWE415_Double_Free__malloc_free_int64_t_53_good();

	void CWE415_Double_Free__malloc_free_struct_45_good();

	void CWE415_Double_Free__malloc_free_int_22_good();

	void CWE415_Double_Free__malloc_free_struct_32_good();

	void CWE415_Double_Free__malloc_free_int_61_good();

	void CWE415_Double_Free__malloc_free_int_11_good();

	void CWE415_Double_Free__malloc_free_long_66_good();

	void CWE415_Double_Free__malloc_free_int64_t_34_good();

	void CWE415_Double_Free__malloc_free_wchar_t_13_good();

	void CWE415_Double_Free__malloc_free_int64_t_17_good();

	void CWE415_Double_Free__malloc_free_char_18_good();

	void CWE415_Double_Free__malloc_free_wchar_t_53_good();

	void CWE415_Double_Free__malloc_free_wchar_t_54_good();

	void CWE415_Double_Free__malloc_free_long_04_good();

	void CWE415_Double_Free__malloc_free_long_63_good();

	void CWE415_Double_Free__malloc_free_char_01_good();

	void CWE415_Double_Free__malloc_free_char_42_good();

	void CWE415_Double_Free__malloc_free_struct_02_good();

	void CWE415_Double_Free__malloc_free_char_31_good();

	void CWE415_Double_Free__malloc_free_struct_44_good();

	void CWE415_Double_Free__malloc_free_int_18_good();

	void CWE415_Double_Free__malloc_free_long_02_good();

	void CWE415_Double_Free__malloc_free_struct_51_good();

	void CWE415_Double_Free__malloc_free_int_03_good();

	void CWE415_Double_Free__malloc_free_wchar_t_51_good();

	void CWE415_Double_Free__malloc_free_int64_t_11_good();

	void CWE415_Double_Free__malloc_free_long_65_good();

	void CWE415_Double_Free__malloc_free_long_01_good();

	void CWE415_Double_Free__malloc_free_char_21_good();

	void CWE415_Double_Free__malloc_free_long_14_good();

	void CWE415_Double_Free__malloc_free_int64_t_01_good();

	void CWE415_Double_Free__malloc_free_long_54_good();

	void CWE415_Double_Free__malloc_free_struct_09_good();

	void CWE415_Double_Free__malloc_free_struct_31_good();

	void CWE415_Double_Free__malloc_free_long_05_good();

	void CWE415_Double_Free__malloc_free_int_65_good();

	void CWE415_Double_Free__malloc_free_int64_t_21_good();

	void CWE415_Double_Free__malloc_free_struct_21_good();

	void CWE415_Double_Free__malloc_free_wchar_t_31_good();

	void CWE415_Double_Free__malloc_free_int64_t_10_good();

	void CWE415_Double_Free__malloc_free_long_68_good();

	void CWE415_Double_Free__malloc_free_char_54_good();

	void CWE415_Double_Free__malloc_free_wchar_t_01_good();

	void CWE415_Double_Free__malloc_free_wchar_t_07_good();

	void CWE415_Double_Free__malloc_free_wchar_t_64_good();

	void CWE415_Double_Free__malloc_free_wchar_t_45_good();

	void CWE415_Double_Free__malloc_free_char_64_good();

	void CWE415_Double_Free__malloc_free_wchar_t_32_good();

	void CWE415_Double_Free__malloc_free_wchar_t_17_good();

	void CWE415_Double_Free__malloc_free_char_51_good();

	void CWE415_Double_Free__malloc_free_int_51_good();

	void CWE415_Double_Free__malloc_free_char_08_good();

	void CWE415_Double_Free__malloc_free_long_18_good();

	void CWE415_Double_Free__malloc_free_wchar_t_06_good();

	void CWE415_Double_Free__malloc_free_long_45_good();

	void CWE415_Double_Free__malloc_free_char_66_good();

	void CWE415_Double_Free__malloc_free_int64_t_14_good();

	void CWE415_Double_Free__malloc_free_wchar_t_67_good();

	void CWE415_Double_Free__malloc_free_int64_t_51_good();

	void CWE415_Double_Free__malloc_free_long_61_good();

	void CWE415_Double_Free__malloc_free_wchar_t_10_good();

	void CWE415_Double_Free__malloc_free_char_67_good();

	void CWE415_Double_Free__malloc_free_struct_41_good();

	void CWE415_Double_Free__malloc_free_wchar_t_18_good();

	void CWE415_Double_Free__malloc_free_struct_54_good();

	void CWE415_Double_Free__malloc_free_wchar_t_41_good();

	void CWE415_Double_Free__malloc_free_long_52_good();

	void CWE415_Double_Free__malloc_free_char_45_good();

	void CWE415_Double_Free__malloc_free_long_31_good();

	void CWE415_Double_Free__malloc_free_char_10_good();

	void CWE415_Double_Free__malloc_free_char_14_good();

	void CWE415_Double_Free__malloc_free_int64_t_45_good();

	void CWE415_Double_Free__malloc_free_wchar_t_63_good();

	void CWE415_Double_Free__malloc_free_struct_68_good();

	void CWE415_Double_Free__malloc_free_struct_08_good();

	void CWE415_Double_Free__malloc_free_char_61_good();

	void CWE415_Double_Free__malloc_free_struct_13_good();

	void CWE415_Double_Free__malloc_free_wchar_t_15_good();

	void CWE415_Double_Free__malloc_free_int64_t_67_good();

	void CWE415_Double_Free__malloc_free_char_04_good();

	void CWE415_Double_Free__malloc_free_int64_t_61_good();

	void CWE415_Double_Free__malloc_free_int_16_good();

	void CWE415_Double_Free__malloc_free_struct_67_good();

	void CWE415_Double_Free__malloc_free_int_34_good();

	void CWE415_Double_Free__malloc_free_long_06_good();

	void CWE415_Double_Free__malloc_free_long_07_good();

	void CWE415_Double_Free__malloc_free_int_09_good();

	void CWE415_Double_Free__malloc_free_int_44_good();

	void CWE415_Double_Free__malloc_free_int_04_good();

	void CWE415_Double_Free__malloc_free_char_52_good();

	void CWE415_Double_Free__malloc_free_int_45_good();

	void CWE415_Double_Free__malloc_free_int64_t_54_good();

	void CWE415_Double_Free__malloc_free_int_66_good();

	void CWE415_Double_Free__malloc_free_struct_05_good();

	void CWE415_Double_Free__malloc_free_wchar_t_66_good();

	void CWE415_Double_Free__malloc_free_char_02_good();

	void CWE415_Double_Free__malloc_free_int64_t_41_good();

	void CWE415_Double_Free__malloc_free_char_11_good();

	void CWE415_Double_Free__malloc_free_int64_t_06_good();

	void CWE415_Double_Free__malloc_free_long_13_good();

	void CWE415_Double_Free__malloc_free_wchar_t_14_good();

	void CWE415_Double_Free__malloc_free_wchar_t_68_good();

	void CWE415_Double_Free__malloc_free_int_15_good();

	void CWE415_Double_Free__malloc_free_int64_t_65_good();

	void CWE415_Double_Free__malloc_free_long_16_good();

	void CWE415_Double_Free__malloc_free_char_12_good();

	void CWE415_Double_Free__malloc_free_long_22_good();

	void CWE415_Double_Free__malloc_free_char_22_good();

	void CWE415_Double_Free__malloc_free_int64_t_32_good();

	void CWE415_Double_Free__malloc_free_int64_t_05_good();

	void CWE415_Double_Free__malloc_free_wchar_t_05_good();

	void CWE415_Double_Free__malloc_free_long_03_good();

	void CWE415_Double_Free__malloc_free_char_65_good();

	void CWE415_Double_Free__malloc_free_struct_11_good();

	void CWE415_Double_Free__malloc_free_struct_01_good();

	void CWE415_Double_Free__malloc_free_struct_63_good();

	void CWE415_Double_Free__malloc_free_int_08_good();

	void CWE415_Double_Free__malloc_free_int64_t_42_good();

	void CWE415_Double_Free__malloc_free_wchar_t_65_good();

	void CWE415_Double_Free__malloc_free_long_41_good();

	void CWE415_Double_Free__malloc_free_struct_06_good();

	void CWE415_Double_Free__malloc_free_int_01_good();

	void CWE415_Double_Free__malloc_free_char_32_good();

	void CWE415_Double_Free__malloc_free_int64_t_63_good();

	void CWE415_Double_Free__malloc_free_int64_t_68_good();

	void CWE415_Double_Free__malloc_free_long_32_good();

	void CWE415_Double_Free__malloc_free_int64_t_04_good();

	void CWE415_Double_Free__malloc_free_struct_18_good();

	void CWE415_Double_Free__malloc_free_int_52_good();

	void CWE415_Double_Free__malloc_free_char_16_good();

	void CWE415_Double_Free__malloc_free_int_14_good();

	void CWE415_Double_Free__malloc_free_wchar_t_52_good();

	void CWE415_Double_Free__malloc_free_wchar_t_11_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE415_Double_Free__malloc_free_struct_61_bad();

	void CWE415_Double_Free__malloc_free_int64_t_15_bad();

	void CWE415_Double_Free__malloc_free_int64_t_13_bad();

	void CWE415_Double_Free__malloc_free_long_64_bad();

	void CWE415_Double_Free__malloc_free_struct_10_bad();

	void CWE415_Double_Free__malloc_free_int_63_bad();

	void CWE415_Double_Free__malloc_free_int_02_bad();

	void CWE415_Double_Free__malloc_free_struct_12_bad();

	void CWE415_Double_Free__malloc_free_struct_22_bad();

	void CWE415_Double_Free__malloc_free_int_10_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_42_bad();

	void CWE415_Double_Free__malloc_free_char_17_bad();

	void CWE415_Double_Free__malloc_free_long_09_bad();

	void CWE415_Double_Free__malloc_free_long_53_bad();

	void CWE415_Double_Free__malloc_free_int_32_bad();

	void CWE415_Double_Free__malloc_free_int_17_bad();

	void CWE415_Double_Free__malloc_free_int_64_bad();

	void CWE415_Double_Free__malloc_free_int_54_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_16_bad();

	void CWE415_Double_Free__malloc_free_long_42_bad();

	void CWE415_Double_Free__malloc_free_int64_t_22_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_21_bad();

	void CWE415_Double_Free__malloc_free_struct_17_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_61_bad();

	void CWE415_Double_Free__malloc_free_struct_65_bad();

	void CWE415_Double_Free__malloc_free_int_41_bad();

	void CWE415_Double_Free__malloc_free_long_15_bad();

	void CWE415_Double_Free__malloc_free_struct_15_bad();

	void CWE415_Double_Free__malloc_free_char_41_bad();

	void CWE415_Double_Free__malloc_free_long_17_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_12_bad();

	void CWE415_Double_Free__malloc_free_int64_t_31_bad();

	void CWE415_Double_Free__malloc_free_int64_t_07_bad();

	void CWE415_Double_Free__malloc_free_long_12_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_03_bad();

	void CWE415_Double_Free__malloc_free_int_67_bad();

	void CWE415_Double_Free__malloc_free_char_03_bad();

	void CWE415_Double_Free__malloc_free_struct_66_bad();

	void CWE415_Double_Free__malloc_free_int_12_bad();

	void CWE415_Double_Free__malloc_free_char_06_bad();

	void CWE415_Double_Free__malloc_free_struct_52_bad();

	void CWE415_Double_Free__malloc_free_int_13_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_08_bad();

	void CWE415_Double_Free__malloc_free_int64_t_12_bad();

	void CWE415_Double_Free__malloc_free_char_53_bad();

	void CWE415_Double_Free__malloc_free_int_06_bad();

	void CWE415_Double_Free__malloc_free_struct_16_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_22_bad();

	void CWE415_Double_Free__malloc_free_int_21_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_04_bad();

	void CWE415_Double_Free__malloc_free_char_34_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_09_bad();

	void CWE415_Double_Free__malloc_free_struct_04_bad();

	void CWE415_Double_Free__malloc_free_char_05_bad();

	void CWE415_Double_Free__malloc_free_int64_t_18_bad();

	void CWE415_Double_Free__malloc_free_char_07_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_02_bad();

	void CWE415_Double_Free__malloc_free_int64_t_09_bad();

	void CWE415_Double_Free__malloc_free_int_07_bad();

	void CWE415_Double_Free__malloc_free_int64_t_52_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_44_bad();

	void CWE415_Double_Free__malloc_free_struct_07_bad();

	void CWE415_Double_Free__malloc_free_long_11_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_34_bad();

	void CWE415_Double_Free__malloc_free_int_68_bad();

	void CWE415_Double_Free__malloc_free_long_44_bad();

	void CWE415_Double_Free__malloc_free_long_10_bad();

	void CWE415_Double_Free__malloc_free_int64_t_44_bad();

	void CWE415_Double_Free__malloc_free_int64_t_64_bad();

	void CWE415_Double_Free__malloc_free_int_05_bad();

	void CWE415_Double_Free__malloc_free_long_67_bad();

	void CWE415_Double_Free__malloc_free_long_34_bad();

	void CWE415_Double_Free__malloc_free_struct_03_bad();

	void CWE415_Double_Free__malloc_free_char_13_bad();

	void CWE415_Double_Free__malloc_free_int_31_bad();

	void CWE415_Double_Free__malloc_free_struct_34_bad();

	void CWE415_Double_Free__malloc_free_char_15_bad();

	void CWE415_Double_Free__malloc_free_char_44_bad();

	void CWE415_Double_Free__malloc_free_int64_t_66_bad();

	void CWE415_Double_Free__malloc_free_int64_t_16_bad();

	void CWE415_Double_Free__malloc_free_char_09_bad();

	void CWE415_Double_Free__malloc_free_long_51_bad();

	void CWE415_Double_Free__malloc_free_char_63_bad();

	void CWE415_Double_Free__malloc_free_struct_14_bad();

	void CWE415_Double_Free__malloc_free_int64_t_02_bad();

	void CWE415_Double_Free__malloc_free_int64_t_03_bad();

	void CWE415_Double_Free__malloc_free_struct_64_bad();

	void CWE415_Double_Free__malloc_free_struct_53_bad();

	void CWE415_Double_Free__malloc_free_struct_42_bad();

	void CWE415_Double_Free__malloc_free_int_42_bad();

	void CWE415_Double_Free__malloc_free_char_68_bad();

	void CWE415_Double_Free__malloc_free_int64_t_08_bad();

	void CWE415_Double_Free__malloc_free_long_21_bad();

	void CWE415_Double_Free__malloc_free_long_08_bad();

	void CWE415_Double_Free__malloc_free_int_53_bad();

	void CWE415_Double_Free__malloc_free_int64_t_53_bad();

	void CWE415_Double_Free__malloc_free_struct_45_bad();

	void CWE415_Double_Free__malloc_free_int_22_bad();

	void CWE415_Double_Free__malloc_free_struct_32_bad();

	void CWE415_Double_Free__malloc_free_int_61_bad();

	void CWE415_Double_Free__malloc_free_int_11_bad();

	void CWE415_Double_Free__malloc_free_long_66_bad();

	void CWE415_Double_Free__malloc_free_int64_t_34_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_13_bad();

	void CWE415_Double_Free__malloc_free_int64_t_17_bad();

	void CWE415_Double_Free__malloc_free_char_18_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_53_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_54_bad();

	void CWE415_Double_Free__malloc_free_long_04_bad();

	void CWE415_Double_Free__malloc_free_long_63_bad();

	void CWE415_Double_Free__malloc_free_char_01_bad();

	void CWE415_Double_Free__malloc_free_char_42_bad();

	void CWE415_Double_Free__malloc_free_struct_02_bad();

	void CWE415_Double_Free__malloc_free_char_31_bad();

	void CWE415_Double_Free__malloc_free_struct_44_bad();

	void CWE415_Double_Free__malloc_free_int_18_bad();

	void CWE415_Double_Free__malloc_free_long_02_bad();

	void CWE415_Double_Free__malloc_free_struct_51_bad();

	void CWE415_Double_Free__malloc_free_int_03_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_51_bad();

	void CWE415_Double_Free__malloc_free_int64_t_11_bad();

	void CWE415_Double_Free__malloc_free_long_65_bad();

	void CWE415_Double_Free__malloc_free_long_01_bad();

	void CWE415_Double_Free__malloc_free_char_21_bad();

	void CWE415_Double_Free__malloc_free_long_14_bad();

	void CWE415_Double_Free__malloc_free_int64_t_01_bad();

	void CWE415_Double_Free__malloc_free_long_54_bad();

	void CWE415_Double_Free__malloc_free_struct_09_bad();

	void CWE415_Double_Free__malloc_free_struct_31_bad();

	void CWE415_Double_Free__malloc_free_long_05_bad();

	void CWE415_Double_Free__malloc_free_int_65_bad();

	void CWE415_Double_Free__malloc_free_int64_t_21_bad();

	void CWE415_Double_Free__malloc_free_struct_21_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_31_bad();

	void CWE415_Double_Free__malloc_free_int64_t_10_bad();

	void CWE415_Double_Free__malloc_free_long_68_bad();

	void CWE415_Double_Free__malloc_free_char_54_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_01_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_07_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_64_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_45_bad();

	void CWE415_Double_Free__malloc_free_char_64_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_32_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_17_bad();

	void CWE415_Double_Free__malloc_free_char_51_bad();

	void CWE415_Double_Free__malloc_free_int_51_bad();

	void CWE415_Double_Free__malloc_free_char_08_bad();

	void CWE415_Double_Free__malloc_free_long_18_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_06_bad();

	void CWE415_Double_Free__malloc_free_long_45_bad();

	void CWE415_Double_Free__malloc_free_char_66_bad();

	void CWE415_Double_Free__malloc_free_int64_t_14_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_67_bad();

	void CWE415_Double_Free__malloc_free_int64_t_51_bad();

	void CWE415_Double_Free__malloc_free_long_61_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_10_bad();

	void CWE415_Double_Free__malloc_free_char_67_bad();

	void CWE415_Double_Free__malloc_free_struct_41_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_18_bad();

	void CWE415_Double_Free__malloc_free_struct_54_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_41_bad();

	void CWE415_Double_Free__malloc_free_long_52_bad();

	void CWE415_Double_Free__malloc_free_char_45_bad();

	void CWE415_Double_Free__malloc_free_long_31_bad();

	void CWE415_Double_Free__malloc_free_char_10_bad();

	void CWE415_Double_Free__malloc_free_char_14_bad();

	void CWE415_Double_Free__malloc_free_int64_t_45_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_63_bad();

	void CWE415_Double_Free__malloc_free_struct_68_bad();

	void CWE415_Double_Free__malloc_free_struct_08_bad();

	void CWE415_Double_Free__malloc_free_char_61_bad();

	void CWE415_Double_Free__malloc_free_struct_13_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_15_bad();

	void CWE415_Double_Free__malloc_free_int64_t_67_bad();

	void CWE415_Double_Free__malloc_free_char_04_bad();

	void CWE415_Double_Free__malloc_free_int64_t_61_bad();

	void CWE415_Double_Free__malloc_free_int_16_bad();

	void CWE415_Double_Free__malloc_free_struct_67_bad();

	void CWE415_Double_Free__malloc_free_int_34_bad();

	void CWE415_Double_Free__malloc_free_long_06_bad();

	void CWE415_Double_Free__malloc_free_long_07_bad();

	void CWE415_Double_Free__malloc_free_int_09_bad();

	void CWE415_Double_Free__malloc_free_int_44_bad();

	void CWE415_Double_Free__malloc_free_int_04_bad();

	void CWE415_Double_Free__malloc_free_char_52_bad();

	void CWE415_Double_Free__malloc_free_int_45_bad();

	void CWE415_Double_Free__malloc_free_int64_t_54_bad();

	void CWE415_Double_Free__malloc_free_int_66_bad();

	void CWE415_Double_Free__malloc_free_struct_05_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_66_bad();

	void CWE415_Double_Free__malloc_free_char_02_bad();

	void CWE415_Double_Free__malloc_free_int64_t_41_bad();

	void CWE415_Double_Free__malloc_free_char_11_bad();

	void CWE415_Double_Free__malloc_free_int64_t_06_bad();

	void CWE415_Double_Free__malloc_free_long_13_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_14_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_68_bad();

	void CWE415_Double_Free__malloc_free_int_15_bad();

	void CWE415_Double_Free__malloc_free_int64_t_65_bad();

	void CWE415_Double_Free__malloc_free_long_16_bad();

	void CWE415_Double_Free__malloc_free_char_12_bad();

	void CWE415_Double_Free__malloc_free_long_22_bad();

	void CWE415_Double_Free__malloc_free_char_22_bad();

	void CWE415_Double_Free__malloc_free_int64_t_32_bad();

	void CWE415_Double_Free__malloc_free_int64_t_05_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_05_bad();

	void CWE415_Double_Free__malloc_free_long_03_bad();

	void CWE415_Double_Free__malloc_free_char_65_bad();

	void CWE415_Double_Free__malloc_free_struct_11_bad();

	void CWE415_Double_Free__malloc_free_struct_01_bad();

	void CWE415_Double_Free__malloc_free_struct_63_bad();

	void CWE415_Double_Free__malloc_free_int_08_bad();

	void CWE415_Double_Free__malloc_free_int64_t_42_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_65_bad();

	void CWE415_Double_Free__malloc_free_long_41_bad();

	void CWE415_Double_Free__malloc_free_struct_06_bad();

	void CWE415_Double_Free__malloc_free_int_01_bad();

	void CWE415_Double_Free__malloc_free_char_32_bad();

	void CWE415_Double_Free__malloc_free_int64_t_63_bad();

	void CWE415_Double_Free__malloc_free_int64_t_68_bad();

	void CWE415_Double_Free__malloc_free_long_32_bad();

	void CWE415_Double_Free__malloc_free_int64_t_04_bad();

	void CWE415_Double_Free__malloc_free_struct_18_bad();

	void CWE415_Double_Free__malloc_free_int_52_bad();

	void CWE415_Double_Free__malloc_free_char_16_bad();

	void CWE415_Double_Free__malloc_free_int_14_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_52_bad();

	void CWE415_Double_Free__malloc_free_wchar_t_11_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
