/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_06_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_06_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_08_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_08_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_03_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_03_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_10_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_10_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_64_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_64_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_13_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_13_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_02_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_02_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_18_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_18_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_12_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_12_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_63_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_63_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_15_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_15_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_16_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_16_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_01_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_01_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_04_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_04_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_07_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_07_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_14_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_14_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_05_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_05_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_11_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_11_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_17_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_17_good();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_09_good();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_09_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_06_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_06_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_08_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_08_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_03_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_03_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_10_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_10_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_64_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_64_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_13_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_13_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_02_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_02_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_18_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_18_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_12_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_12_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_63_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_63_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_15_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_15_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_16_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_16_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_01_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_01_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_04_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_04_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_07_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_07_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_14_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_14_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_05_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_05_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_11_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_11_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_17_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_17_bad();

	printLine("Calling CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_09_bad();");
	CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_09_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
