// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_06_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_08_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_03_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_10_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_64_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_13_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_02_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_18_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_12_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_63_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_15_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_16_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_01_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_04_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_07_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_14_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_05_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_11_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_17_good();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_09_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_06_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_08_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_03_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_10_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_64_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_13_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_02_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_18_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_12_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_63_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_15_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_16_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_01_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_04_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_07_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_14_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_05_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_11_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_17_bad();

	void CWE457_Use_of_Uninitialized_Variable__wchar_t_pointer_09_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
