/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_63_good();");
	CWE476_NULL_Pointer_Dereference__struct_63_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_01_good();");
	CWE476_NULL_Pointer_Dereference__char_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_45_good();");
	CWE476_NULL_Pointer_Dereference__struct_45_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_09_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_13_good();");
	CWE476_NULL_Pointer_Dereference__struct_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_32_good();");
	CWE476_NULL_Pointer_Dereference__struct_32_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_06_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_31_good();");
	CWE476_NULL_Pointer_Dereference__struct_31_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_02_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_41_good();");
	CWE476_NULL_Pointer_Dereference__char_41_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_22_good();");
	CWE476_NULL_Pointer_Dereference__int_22_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_04_good();");
	CWE476_NULL_Pointer_Dereference__long_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_22_good();");
	CWE476_NULL_Pointer_Dereference__long_22_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_15_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_63_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_63_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_17_good();");
	CWE476_NULL_Pointer_Dereference__long_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_14_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_07_good();");
	CWE476_NULL_Pointer_Dereference__long_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_05_good();");
	CWE476_NULL_Pointer_Dereference__struct_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_65_good();");
	CWE476_NULL_Pointer_Dereference__char_65_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_22_good();");
	CWE476_NULL_Pointer_Dereference__char_22_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_11_good();");
	CWE476_NULL_Pointer_Dereference__char_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_08_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_17_good();");
	CWE476_NULL_Pointer_Dereference__int_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_14_good();");
	CWE476_NULL_Pointer_Dereference__struct_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_13_good();");
	CWE476_NULL_Pointer_Dereference__long_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_67_good();");
	CWE476_NULL_Pointer_Dereference__long_67_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_34_good();");
	CWE476_NULL_Pointer_Dereference__long_34_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_17_good();");
	CWE476_NULL_Pointer_Dereference__struct_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_65_good();");
	CWE476_NULL_Pointer_Dereference__long_65_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_12_good();");
	CWE476_NULL_Pointer_Dereference__struct_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_51_good();");
	CWE476_NULL_Pointer_Dereference__struct_51_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_41_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_41_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_52_good();");
	CWE476_NULL_Pointer_Dereference__char_52_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_15_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_15_good();");
	CWE476_NULL_Pointer_Dereference__struct_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_16_good();");
	CWE476_NULL_Pointer_Dereference__struct_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_10_good();");
	CWE476_NULL_Pointer_Dereference__char_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_64_good();");
	CWE476_NULL_Pointer_Dereference__long_64_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_12_good();");
	CWE476_NULL_Pointer_Dereference__char_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_08_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_52_good();");
	CWE476_NULL_Pointer_Dereference__struct_52_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_14_good();");
	CWE476_NULL_Pointer_Dereference__long_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_15_good();");
	CWE476_NULL_Pointer_Dereference__char_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_03_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_52_good();");
	CWE476_NULL_Pointer_Dereference__long_52_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_16_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_01_good();");
	CWE476_NULL_Pointer_Dereference__long_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_08_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_02_good();");
	CWE476_NULL_Pointer_Dereference__int_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_06_good();");
	CWE476_NULL_Pointer_Dereference__long_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_05_good();");
	CWE476_NULL_Pointer_Dereference__char_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_68_good();");
	CWE476_NULL_Pointer_Dereference__char_68_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_16_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_03_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_03_good();");
	CWE476_NULL_Pointer_Dereference__int_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_68_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_68_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_51_good();");
	CWE476_NULL_Pointer_Dereference__long_51_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_06_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_44_good();");
	CWE476_NULL_Pointer_Dereference__int_44_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_64_good();");
	CWE476_NULL_Pointer_Dereference__struct_64_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_31_good();");
	CWE476_NULL_Pointer_Dereference__int_31_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_17_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_14_good();");
	CWE476_NULL_Pointer_Dereference__char_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_12_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_12_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_07_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_09_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_09_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_09_good();");
	CWE476_NULL_Pointer_Dereference__char_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_03_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_54_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_54_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_66_good();");
	CWE476_NULL_Pointer_Dereference__long_66_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_12_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_10_good();");
	CWE476_NULL_Pointer_Dereference__int_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_17_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_66_good();");
	CWE476_NULL_Pointer_Dereference__char_66_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_14_good();");
	CWE476_NULL_Pointer_Dereference__int_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_07_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_11_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_17_good();");
	CWE476_NULL_Pointer_Dereference__char_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_03_good();");
	CWE476_NULL_Pointer_Dereference__struct_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_16_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_17_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_67_good();");
	CWE476_NULL_Pointer_Dereference__struct_67_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_44_good();");
	CWE476_NULL_Pointer_Dereference__char_44_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_22_good();");
	CWE476_NULL_Pointer_Dereference__struct_22_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_08_good();");
	CWE476_NULL_Pointer_Dereference__long_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_08_good();");
	CWE476_NULL_Pointer_Dereference__struct_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_68_good();");
	CWE476_NULL_Pointer_Dereference__long_68_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_05_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_18_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_05_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_44_good();");
	CWE476_NULL_Pointer_Dereference__long_44_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_02_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_04_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_68_good();");
	CWE476_NULL_Pointer_Dereference__struct_68_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_16_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_05_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_64_good();");
	CWE476_NULL_Pointer_Dereference__int_64_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_09_good();");
	CWE476_NULL_Pointer_Dereference__long_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_63_good();");
	CWE476_NULL_Pointer_Dereference__char_63_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_63_good();");
	CWE476_NULL_Pointer_Dereference__long_63_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_54_good();");
	CWE476_NULL_Pointer_Dereference__struct_54_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_06_good();");
	CWE476_NULL_Pointer_Dereference__int_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_02_good();");
	CWE476_NULL_Pointer_Dereference__struct_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_11_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_04_good();");
	CWE476_NULL_Pointer_Dereference__char_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_10_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_31_good();");
	CWE476_NULL_Pointer_Dereference__long_31_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_18_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_18_good();");
	CWE476_NULL_Pointer_Dereference__struct_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_13_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_66_good();");
	CWE476_NULL_Pointer_Dereference__struct_66_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_41_good();");
	CWE476_NULL_Pointer_Dereference__struct_41_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_05_good();");
	CWE476_NULL_Pointer_Dereference__long_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_02_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_04_good();");
	CWE476_NULL_Pointer_Dereference__int_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_10_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_51_good();");
	CWE476_NULL_Pointer_Dereference__int_51_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_06_good();");
	CWE476_NULL_Pointer_Dereference__struct_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_45_good();");
	CWE476_NULL_Pointer_Dereference__char_45_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_11_good();");
	CWE476_NULL_Pointer_Dereference__struct_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_64_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_64_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_08_good();");
	CWE476_NULL_Pointer_Dereference__int_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_44_good();");
	CWE476_NULL_Pointer_Dereference__struct_44_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_32_good();");
	CWE476_NULL_Pointer_Dereference__long_32_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_16_good();");
	CWE476_NULL_Pointer_Dereference__long_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_01_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_01_good();");
	CWE476_NULL_Pointer_Dereference__struct_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_53_good();");
	CWE476_NULL_Pointer_Dereference__long_53_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_03_good();");
	CWE476_NULL_Pointer_Dereference__long_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_03_good();");
	CWE476_NULL_Pointer_Dereference__char_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_31_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_31_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_01_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_04_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_11_good();");
	CWE476_NULL_Pointer_Dereference__long_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_21_good();");
	CWE476_NULL_Pointer_Dereference__int_21_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_15_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_18_good();");
	CWE476_NULL_Pointer_Dereference__char_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_01_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_32_good();");
	CWE476_NULL_Pointer_Dereference__char_32_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_51_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_51_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_21_good();");
	CWE476_NULL_Pointer_Dereference__char_21_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_01_good();");
	CWE476_NULL_Pointer_Dereference__int_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_12_good();");
	CWE476_NULL_Pointer_Dereference__long_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_65_good();");
	CWE476_NULL_Pointer_Dereference__int_65_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_41_good();");
	CWE476_NULL_Pointer_Dereference__int_41_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_31_good();");
	CWE476_NULL_Pointer_Dereference__char_31_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_07_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_04_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_63_good();");
	CWE476_NULL_Pointer_Dereference__int_63_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_16_good();");
	CWE476_NULL_Pointer_Dereference__char_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_14_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_54_good();");
	CWE476_NULL_Pointer_Dereference__long_54_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_02_good();");
	CWE476_NULL_Pointer_Dereference__char_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_65_good();");
	CWE476_NULL_Pointer_Dereference__struct_65_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_18_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_45_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_45_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_53_good();");
	CWE476_NULL_Pointer_Dereference__struct_53_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_52_good();");
	CWE476_NULL_Pointer_Dereference__int_52_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_51_good();");
	CWE476_NULL_Pointer_Dereference__char_51_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_09_good();");
	CWE476_NULL_Pointer_Dereference__int_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_06_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_13_good();");
	CWE476_NULL_Pointer_Dereference__char_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_34_good();");
	CWE476_NULL_Pointer_Dereference__char_34_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_08_good();");
	CWE476_NULL_Pointer_Dereference__char_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_18_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_21_good();");
	CWE476_NULL_Pointer_Dereference__long_21_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_32_good();");
	CWE476_NULL_Pointer_Dereference__int_32_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_45_good();");
	CWE476_NULL_Pointer_Dereference__int_45_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_65_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_65_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_15_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_16_good();");
	CWE476_NULL_Pointer_Dereference__int_16_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_68_good();");
	CWE476_NULL_Pointer_Dereference__int_68_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_45_good();");
	CWE476_NULL_Pointer_Dereference__long_45_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_06_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_13_good();");
	CWE476_NULL_Pointer_Dereference__int_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_07_good();");
	CWE476_NULL_Pointer_Dereference__int_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_66_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_66_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_67_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_67_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_06_good();");
	CWE476_NULL_Pointer_Dereference__char_06_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_05_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_54_good();");
	CWE476_NULL_Pointer_Dereference__char_54_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_08_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_08_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_05_good();");
	CWE476_NULL_Pointer_Dereference__int_05_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_03_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_03_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_10_good();");
	CWE476_NULL_Pointer_Dereference__struct_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_09_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_34_good();");
	CWE476_NULL_Pointer_Dereference__struct_34_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_10_good();");
	CWE476_NULL_Pointer_Dereference__long_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_02_good();");
	CWE476_NULL_Pointer_Dereference__long_02_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_22_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_22_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_64_good();");
	CWE476_NULL_Pointer_Dereference__char_64_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_21_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_21_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_14_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_14_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_53_good();");
	CWE476_NULL_Pointer_Dereference__char_53_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_21_good();");
	CWE476_NULL_Pointer_Dereference__struct_21_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_52_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_52_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_18_good();");
	CWE476_NULL_Pointer_Dereference__int_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_17_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_17_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_04_good();");
	CWE476_NULL_Pointer_Dereference__struct_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_07_good();");
	CWE476_NULL_Pointer_Dereference__struct_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_07_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_13_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_67_good();");
	CWE476_NULL_Pointer_Dereference__int_67_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_67_good();");
	CWE476_NULL_Pointer_Dereference__char_67_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_34_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_34_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_11_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_09_good();");
	CWE476_NULL_Pointer_Dereference__struct_09_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_32_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_32_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_12_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_10_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_54_good();");
	CWE476_NULL_Pointer_Dereference__int_54_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_13_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_13_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_66_good();");
	CWE476_NULL_Pointer_Dereference__int_66_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_11_good();");
	CWE476_NULL_Pointer_Dereference__int_11_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_10_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_10_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_44_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_44_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_34_good();");
	CWE476_NULL_Pointer_Dereference__int_34_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_12_good();");
	CWE476_NULL_Pointer_Dereference__int_12_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_15_good();");
	CWE476_NULL_Pointer_Dereference__int_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_15_good();");
	CWE476_NULL_Pointer_Dereference__long_15_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_18_good();");
	CWE476_NULL_Pointer_Dereference__long_18_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_41_good();");
	CWE476_NULL_Pointer_Dereference__long_41_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_07_good();");
	CWE476_NULL_Pointer_Dereference__char_07_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_53_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_53_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_53_good();");
	CWE476_NULL_Pointer_Dereference__int_53_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_63_bad();");
	CWE476_NULL_Pointer_Dereference__struct_63_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_01_bad();");
	CWE476_NULL_Pointer_Dereference__char_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_45_bad();");
	CWE476_NULL_Pointer_Dereference__struct_45_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_09_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_13_bad();");
	CWE476_NULL_Pointer_Dereference__struct_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_32_bad();");
	CWE476_NULL_Pointer_Dereference__struct_32_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_06_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_31_bad();");
	CWE476_NULL_Pointer_Dereference__struct_31_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_02_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_41_bad();");
	CWE476_NULL_Pointer_Dereference__char_41_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_22_bad();");
	CWE476_NULL_Pointer_Dereference__int_22_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_04_bad();");
	CWE476_NULL_Pointer_Dereference__long_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_22_bad();");
	CWE476_NULL_Pointer_Dereference__long_22_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_15_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_63_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_63_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_17_bad();");
	CWE476_NULL_Pointer_Dereference__long_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_14_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_07_bad();");
	CWE476_NULL_Pointer_Dereference__long_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_05_bad();");
	CWE476_NULL_Pointer_Dereference__struct_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_65_bad();");
	CWE476_NULL_Pointer_Dereference__char_65_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_22_bad();");
	CWE476_NULL_Pointer_Dereference__char_22_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_11_bad();");
	CWE476_NULL_Pointer_Dereference__char_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_08_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_17_bad();");
	CWE476_NULL_Pointer_Dereference__int_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_14_bad();");
	CWE476_NULL_Pointer_Dereference__struct_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_13_bad();");
	CWE476_NULL_Pointer_Dereference__long_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_67_bad();");
	CWE476_NULL_Pointer_Dereference__long_67_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_34_bad();");
	CWE476_NULL_Pointer_Dereference__long_34_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_17_bad();");
	CWE476_NULL_Pointer_Dereference__struct_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_65_bad();");
	CWE476_NULL_Pointer_Dereference__long_65_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_12_bad();");
	CWE476_NULL_Pointer_Dereference__struct_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_51_bad();");
	CWE476_NULL_Pointer_Dereference__struct_51_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_41_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_41_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_52_bad();");
	CWE476_NULL_Pointer_Dereference__char_52_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_15_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_15_bad();");
	CWE476_NULL_Pointer_Dereference__struct_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_16_bad();");
	CWE476_NULL_Pointer_Dereference__struct_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_10_bad();");
	CWE476_NULL_Pointer_Dereference__char_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_64_bad();");
	CWE476_NULL_Pointer_Dereference__long_64_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_12_bad();");
	CWE476_NULL_Pointer_Dereference__char_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_08_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_52_bad();");
	CWE476_NULL_Pointer_Dereference__struct_52_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_14_bad();");
	CWE476_NULL_Pointer_Dereference__long_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_15_bad();");
	CWE476_NULL_Pointer_Dereference__char_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_03_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_52_bad();");
	CWE476_NULL_Pointer_Dereference__long_52_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_16_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_01_bad();");
	CWE476_NULL_Pointer_Dereference__long_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_08_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_02_bad();");
	CWE476_NULL_Pointer_Dereference__int_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_06_bad();");
	CWE476_NULL_Pointer_Dereference__long_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_05_bad();");
	CWE476_NULL_Pointer_Dereference__char_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_68_bad();");
	CWE476_NULL_Pointer_Dereference__char_68_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_16_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_03_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_03_bad();");
	CWE476_NULL_Pointer_Dereference__int_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_68_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_68_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_51_bad();");
	CWE476_NULL_Pointer_Dereference__long_51_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_06_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_44_bad();");
	CWE476_NULL_Pointer_Dereference__int_44_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_64_bad();");
	CWE476_NULL_Pointer_Dereference__struct_64_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_31_bad();");
	CWE476_NULL_Pointer_Dereference__int_31_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_17_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_14_bad();");
	CWE476_NULL_Pointer_Dereference__char_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_12_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_12_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_07_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_09_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_09_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_09_bad();");
	CWE476_NULL_Pointer_Dereference__char_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_03_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_54_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_54_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_66_bad();");
	CWE476_NULL_Pointer_Dereference__long_66_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_12_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_10_bad();");
	CWE476_NULL_Pointer_Dereference__int_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_17_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_66_bad();");
	CWE476_NULL_Pointer_Dereference__char_66_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_14_bad();");
	CWE476_NULL_Pointer_Dereference__int_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_07_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_11_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_17_bad();");
	CWE476_NULL_Pointer_Dereference__char_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_03_bad();");
	CWE476_NULL_Pointer_Dereference__struct_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_16_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_17_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_67_bad();");
	CWE476_NULL_Pointer_Dereference__struct_67_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_44_bad();");
	CWE476_NULL_Pointer_Dereference__char_44_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_22_bad();");
	CWE476_NULL_Pointer_Dereference__struct_22_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_08_bad();");
	CWE476_NULL_Pointer_Dereference__long_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_08_bad();");
	CWE476_NULL_Pointer_Dereference__struct_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_68_bad();");
	CWE476_NULL_Pointer_Dereference__long_68_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_05_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_18_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_05_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_44_bad();");
	CWE476_NULL_Pointer_Dereference__long_44_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_02_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_04_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_68_bad();");
	CWE476_NULL_Pointer_Dereference__struct_68_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_16_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_05_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_64_bad();");
	CWE476_NULL_Pointer_Dereference__int_64_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_09_bad();");
	CWE476_NULL_Pointer_Dereference__long_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_63_bad();");
	CWE476_NULL_Pointer_Dereference__char_63_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_63_bad();");
	CWE476_NULL_Pointer_Dereference__long_63_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_54_bad();");
	CWE476_NULL_Pointer_Dereference__struct_54_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_06_bad();");
	CWE476_NULL_Pointer_Dereference__int_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_02_bad();");
	CWE476_NULL_Pointer_Dereference__struct_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_11_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_04_bad();");
	CWE476_NULL_Pointer_Dereference__char_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_10_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_31_bad();");
	CWE476_NULL_Pointer_Dereference__long_31_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_18_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_18_bad();");
	CWE476_NULL_Pointer_Dereference__struct_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_13_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_66_bad();");
	CWE476_NULL_Pointer_Dereference__struct_66_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_41_bad();");
	CWE476_NULL_Pointer_Dereference__struct_41_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_05_bad();");
	CWE476_NULL_Pointer_Dereference__long_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_02_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_04_bad();");
	CWE476_NULL_Pointer_Dereference__int_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_10_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_51_bad();");
	CWE476_NULL_Pointer_Dereference__int_51_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_06_bad();");
	CWE476_NULL_Pointer_Dereference__struct_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_45_bad();");
	CWE476_NULL_Pointer_Dereference__char_45_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_11_bad();");
	CWE476_NULL_Pointer_Dereference__struct_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_64_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_64_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_08_bad();");
	CWE476_NULL_Pointer_Dereference__int_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_44_bad();");
	CWE476_NULL_Pointer_Dereference__struct_44_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_32_bad();");
	CWE476_NULL_Pointer_Dereference__long_32_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_16_bad();");
	CWE476_NULL_Pointer_Dereference__long_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_01_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_01_bad();");
	CWE476_NULL_Pointer_Dereference__struct_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_53_bad();");
	CWE476_NULL_Pointer_Dereference__long_53_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_03_bad();");
	CWE476_NULL_Pointer_Dereference__long_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_03_bad();");
	CWE476_NULL_Pointer_Dereference__char_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_31_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_31_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_01_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_04_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_11_bad();");
	CWE476_NULL_Pointer_Dereference__long_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_21_bad();");
	CWE476_NULL_Pointer_Dereference__int_21_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_15_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_18_bad();");
	CWE476_NULL_Pointer_Dereference__char_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_01_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_32_bad();");
	CWE476_NULL_Pointer_Dereference__char_32_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_51_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_51_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_21_bad();");
	CWE476_NULL_Pointer_Dereference__char_21_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_01_bad();");
	CWE476_NULL_Pointer_Dereference__int_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_12_bad();");
	CWE476_NULL_Pointer_Dereference__long_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_65_bad();");
	CWE476_NULL_Pointer_Dereference__int_65_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_41_bad();");
	CWE476_NULL_Pointer_Dereference__int_41_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_31_bad();");
	CWE476_NULL_Pointer_Dereference__char_31_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_07_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_04_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_63_bad();");
	CWE476_NULL_Pointer_Dereference__int_63_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_16_bad();");
	CWE476_NULL_Pointer_Dereference__char_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_14_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_54_bad();");
	CWE476_NULL_Pointer_Dereference__long_54_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_02_bad();");
	CWE476_NULL_Pointer_Dereference__char_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_65_bad();");
	CWE476_NULL_Pointer_Dereference__struct_65_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_18_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_45_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_45_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_53_bad();");
	CWE476_NULL_Pointer_Dereference__struct_53_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_52_bad();");
	CWE476_NULL_Pointer_Dereference__int_52_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_51_bad();");
	CWE476_NULL_Pointer_Dereference__char_51_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_09_bad();");
	CWE476_NULL_Pointer_Dereference__int_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_06_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_13_bad();");
	CWE476_NULL_Pointer_Dereference__char_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_34_bad();");
	CWE476_NULL_Pointer_Dereference__char_34_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_08_bad();");
	CWE476_NULL_Pointer_Dereference__char_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_18_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_21_bad();");
	CWE476_NULL_Pointer_Dereference__long_21_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_32_bad();");
	CWE476_NULL_Pointer_Dereference__int_32_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_45_bad();");
	CWE476_NULL_Pointer_Dereference__int_45_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_65_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_65_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_15_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_16_bad();");
	CWE476_NULL_Pointer_Dereference__int_16_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_68_bad();");
	CWE476_NULL_Pointer_Dereference__int_68_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_45_bad();");
	CWE476_NULL_Pointer_Dereference__long_45_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_06_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_13_bad();");
	CWE476_NULL_Pointer_Dereference__int_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_07_bad();");
	CWE476_NULL_Pointer_Dereference__int_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_66_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_66_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_67_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_67_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_06_bad();");
	CWE476_NULL_Pointer_Dereference__char_06_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_05_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_54_bad();");
	CWE476_NULL_Pointer_Dereference__char_54_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_08_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_08_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_05_bad();");
	CWE476_NULL_Pointer_Dereference__int_05_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_03_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_03_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_10_bad();");
	CWE476_NULL_Pointer_Dereference__struct_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_09_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_34_bad();");
	CWE476_NULL_Pointer_Dereference__struct_34_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_10_bad();");
	CWE476_NULL_Pointer_Dereference__long_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_02_bad();");
	CWE476_NULL_Pointer_Dereference__long_02_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_22_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_22_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_64_bad();");
	CWE476_NULL_Pointer_Dereference__char_64_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_21_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_21_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_14_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_14_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_53_bad();");
	CWE476_NULL_Pointer_Dereference__char_53_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_21_bad();");
	CWE476_NULL_Pointer_Dereference__struct_21_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_52_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_52_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_18_bad();");
	CWE476_NULL_Pointer_Dereference__int_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_17_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_17_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_04_bad();");
	CWE476_NULL_Pointer_Dereference__struct_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_07_bad();");
	CWE476_NULL_Pointer_Dereference__struct_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_07_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_13_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_67_bad();");
	CWE476_NULL_Pointer_Dereference__int_67_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_67_bad();");
	CWE476_NULL_Pointer_Dereference__char_67_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_34_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_34_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_11_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_09_bad();");
	CWE476_NULL_Pointer_Dereference__struct_09_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_32_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_32_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_12_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_10_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_54_bad();");
	CWE476_NULL_Pointer_Dereference__int_54_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_13_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_13_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_66_bad();");
	CWE476_NULL_Pointer_Dereference__int_66_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_11_bad();");
	CWE476_NULL_Pointer_Dereference__int_11_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_10_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_10_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_44_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_44_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_34_bad();");
	CWE476_NULL_Pointer_Dereference__int_34_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_12_bad();");
	CWE476_NULL_Pointer_Dereference__int_12_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_15_bad();");
	CWE476_NULL_Pointer_Dereference__int_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_04_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_15_bad();");
	CWE476_NULL_Pointer_Dereference__long_15_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_18_bad();");
	CWE476_NULL_Pointer_Dereference__long_18_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_41_bad();");
	CWE476_NULL_Pointer_Dereference__long_41_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_07_bad();");
	CWE476_NULL_Pointer_Dereference__char_07_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_53_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_53_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_53_bad();");
	CWE476_NULL_Pointer_Dereference__int_53_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
