BUILD=`uname -msr | tr " /" "__"`.d
ISNOTSRCDIR=test ! -f configure



pkgdatadir = $(datadir)/zziplib
pkgincludedir = $(includedir)/zziplib
pkglibdir = $(libdir)/zziplib
pkglibexecdir = $(libexecdir)/zziplib
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
target_triplet = x86_64-unknown-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
 $(srcdir)/Makefile.in $(srcdir)/config.h.in \
 $(top_srcdir)/configure COPYING.LIB ChangeLog TODO \
 uses/config.guess uses/config.sub uses/depcomp uses/install-sh \
 uses/ltmain.sh uses/missing uses/mkinstalldirs
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ac_compile_check_sizeof.m4 \
 $(top_srcdir)/m4/ac_set_default_paths_system.m4 \
 $(top_srcdir)/m4/ac_sys_largefile_sensitive.m4 \
 $(top_srcdir)/m4/acx_restrict.m4 \
 $(top_srcdir)/m4/ax_cflags_gcc_option.m4 \
 $(top_srcdir)/m4/ax_cflags_no_writable_strings.m4 \
 $(top_srcdir)/m4/ax_cflags_strict_prototypes.m4 \
 $(top_srcdir)/m4/ax_cflags_warn_all.m4 \
 $(top_srcdir)/m4/ax_check_aligned_access_required.m4 \
 $(top_srcdir)/m4/ax_configure_args.m4 \
 $(top_srcdir)/m4/ax_create_pkgconfig_info.m4 \
 $(top_srcdir)/m4/ax_enable_builddir_uname.m4 \
 $(top_srcdir)/m4/ax_expand_prefix.m4 \
 $(top_srcdir)/m4/ax_maintainer_mode_auto_silent.m4 \
 $(top_srcdir)/m4/ax_not_enable_frame_pointer.m4 \
 $(top_srcdir)/m4/ax_pax_tar.m4 \
 $(top_srcdir)/m4/ax_prefix_config_h.m4 \
 $(top_srcdir)/m4/ax_set_version_info.m4 \
 $(top_srcdir)/m4/ax_spec_file.m4 \
 $(top_srcdir)/m4/ax_spec_package_version.m4 \
 $(top_srcdir)/m4/ax_warning_default_aclocaldir.m4 \
 $(top_srcdir)/m4/ax_warning_default_pkgconfig.m4 \
 $(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
 $(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
 $(top_srcdir)/m4/lt~obsolete.m4 \
 $(top_srcdir)/m4/patch_libtool_on_darwin_zsh_overquoting.m4 \
 $(top_srcdir)/m4/patch_libtool_sys_lib_search_path_spec.m4 \
 $(top_srcdir)/m4/patch_libtool_to_add_host_cc.m4 \
 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 $(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/uses/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
SOURCES =
DIST_SOURCES =
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
 html-recursive info-recursive install-data-recursive \
 install-dvi-recursive install-exec-recursive \
 install-html-recursive install-info-recursive \
 install-pdf-recursive install-ps-recursive install-recursive \
 installcheck-recursive installdirs-recursive pdf-recursive \
 ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/uses/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/uses/missing --run tar
AR = ar
AS = as
AUTOCONF = sleep 9 ; true || autoconf || skipped
AUTOHEADER = sleep 9 ; true || autoheader || skipped
AUTOMAKE = sleep 9 ; true || automake || skipped
AWK = gawk
CC = clang
CCDEPMODE = depmode=gcc3
CFLAGS =  -O0 -fsanitize=address -D_USE_MMAP  -fomit-frame-pointer -Wall -Wpointer-arith -Wsign-compare -Wmissing-declarations -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wstrict-aliasing -Warray-bounds -Wstrict-prototypes
CONFIG_FILES = 
CPP = clang -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = dlltool
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GNUTAR = :
GREP = /bin/grep
GTAR = :
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LARGEFILE_CFLAGS = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAINT = #
MAKEINFO = ${SHELL} /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/uses/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
MKZIP = /usr/bin/zip
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = zziplib
PACKAGE_BUGREPORT = 
PACKAGE_NAME = zziplib
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 0.13.62
PATH_SEPARATOR = :
PAX = :
PAX_TAR_CREATE = '/bin/tar' cf
PAX_TAR_EXTRACT = '/bin/tar' xf
PERL = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
PYTHON = /usr/bin/python
RANLIB = ranlib
RELEASE_INFO = -release 0
RESOLVES =  # 
SDL = 
SDL_GENERATE = 
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
TAR = /bin/tar
THREAD_SAFE = -thread-safe
VERSION = 0.13.62
VERSION_INFO = -version-info 13:
XMLTO = /usr/bin/xmlto
ZIPTESTS = 
ZLIB_INCL = 
ZLIB_LDIR = 
ZLIB_VERSION = 1.2.11
ZZIPLIB_LDFLAGS = -Wl,--export-dynamic
abs_builddir = /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/Linux_4.15.0-117-generic_x86_64.d
abs_srcdir = /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/Linux_4.15.0-117-generic_x86_64.d/..
abs_top_builddir = /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/Linux_4.15.0-117-generic_x86_64.d
abs_top_srcdir = /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/Linux_4.15.0-117-generic_x86_64.d/..
ac_ct_CC = clang
ac_ct_DUMPBIN = 
aclocaldir = /usr/share/aclocal
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
ax_enable_builddir_sed = sed
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datadir}/doc
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/acesrc/testcase/linuxflaw/zziplib/zziplib-0.13.62/uses/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgconfig_libdir = ${libdir}/pkgconfig
pkgconfig_libfile = zziplib.pc
pkgconfigdir = /usr/lib/pkgconfig
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${sysconfdir}/default
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-unknown-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = unknown
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = 1.4 foreign dist-bzip2
ACLOCAL_AMFLAGS = -I m4
WANT_AUTOMAKE = 1.7
WANT_AUTOCONF = 2.57
DIST_SUBDIRS = zzip zzipwrap bins test docs  SDL
SUBDIRS = zzip zzipwrap bins test docs 
OSC_ROOT = /my/own/osc
OSC_SRCDIR = $(OSC_ROOT)
OSC_PROJECT = home:
OSC_PACKAGE = $(PACKAGE)
OSC_SPECFILE = $(top_srcdir)/$(PACKAGE).spec
OSC_TARBALL = $(PACKAGE)-$(VERSION).tar.bz2
OSC_BUILDDIR = $(OSC_ROOT)
OSC_PACKAGECACHEDIR = $(OSC_BUILDDIR)/packagecache
OSC_BUILDROOT = $(OSC_BUILDDIR)/buildroot
OSC_REPOSITORY = openSUSE_11.2
OSC_ARCH = x86_64
DOIT = :
MSVC8 = msvc8/README.TXT msvc8/zip.exe msvc8/test1.zip msvc8/test.zip \
msvc8/zzdir.vcproj    msvc8/zzipself.vcproj     msvc8/zzip.vcproj \
msvc8/zziplib.sln     msvc8/zzipsetstub.sln     msvc8/zzobfuscated.sln \
msvc8/zziplib.vcproj  msvc8/zzipsetstub.vcproj  msvc8/zzobfuscated.vcproj \
msvc8/zzcat.sln       msvc8/zzipself.bat        msvc8/zzip.sln \
msvc8/zzcat.vcproj    msvc8/zzipself.sln        msvc8/zziptest.sln \
msvc8/zzdir.sln       msvc8/zzipself.txt        msvc8/zziptest.vcproj \
                      msvc8/zzipfseeko.vcproj   msvc8/zzipmmapped.vcproj 

MSVC7 = msvc7/pkzip.exe msvc7/test1.zip msvc7/test.zip \
msvc7/zzdir.vcproj    msvc7/zzipself.vcproj     msvc7/zzip.vcproj \
msvc7/zziplib.sln     msvc7/zzipsetstub.sln     msvc7/zzobfuscated.sln \
msvc7/zziplib.vcproj  msvc7/zzipsetstub.vcproj  msvc7/zzobfuscated.vcproj \
msvc7/zzcat.sln       msvc7/zzipself.bat        msvc7/zzip.sln \
msvc7/zzcat.vcproj    msvc7/zzipself.sln        msvc7/zziptest.sln \
msvc7/zzdir.sln       msvc7/zzipself.txt        msvc7/zziptest.vcproj

MSVC6 = \
msvc6/zzcat.dsp        msvc6/zziplib.dsp      msvc6/zzipwrap.dsp \
msvc6/zzdir.dsp        msvc6/zziplib.dsw      msvc6/zzobfuscated.dsp \
msvc6/zziptest.dsp     msvc6/zzip.dsp  

EXTRA_DIST = zziplib.spec zzipback.sed Makefile.mk \
               $(MSVC8) $(MSVC7) $(MSVC6) $(am__aclocal_m4_deps)

PHONY = auto boottrap rpm doc docs man manpages htmpages sdl testsdl \
 comp compats msvc6 msvc7

_FILE_OFFSET64 = -D_ZZIP_LARGEFILE -D_FILE_OFFSET_BITS=64
_RELEASEINFO64 = "RELEASE_INFO=-release 0-64"
all: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

am--refresh: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
$(srcdir)/Makefile.in: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
Makefile: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

$(top_builddir)/config.status: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

$(top_srcdir)/configure: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
$(ACLOCAL_M4): ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
$(am__aclocal_m4_deps): ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

config.h: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

stamp-h1: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
$(srcdir)/config.h.in: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distclean-hdr: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

mostlyclean-libtool: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

clean-libtool: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distclean-libtool: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

$(RECURSIVE_TARGETS): ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

$(RECURSIVE_CLEAN_TARGETS): ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
tags-recursive: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
ctags-recursive: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

ID: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
tags: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

TAGS: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
ctags: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
CTAGS: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

GTAGS: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distclean-tags: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distdir: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
dist-gzip: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
dist-bzip2: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dist-lzma: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dist-xz: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dist-tarZ: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dist-shar: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dist-zip: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dist dist-all: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distcheck: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
distuninstallcheck: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
distcleancheck: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
check-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
check: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
all-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
installdirs: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
installdirs-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
install: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
install-exec: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
install-data: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
uninstall: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

installcheck: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
install-strip: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
mostlyclean-generic: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

clean-generic: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distclean-generic: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

maintainer-clean-generic: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
clean: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

clean-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

distclean: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
distclean-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dvi: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

dvi-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

html: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

html-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

info: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

info-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-data-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-dvi: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-dvi-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-exec-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-html: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-html-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-info: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-info-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-man: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-pdf: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-pdf-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-ps: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

install-ps-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

installcheck-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

maintainer-clean: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
maintainer-clean-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

mostlyclean: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

mostlyclean-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

pdf: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

pdf-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

ps: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

ps-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

uninstall-am: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"



rpm: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
osc-copy: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
osc-ci osc-commit upload-osc: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

osc-build: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
osc-clean: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
osc-distclean: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

indent-check: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

doc docs docu clean-doc clean-docs clean-docu   zzip.html zzip.xml zzip.pdf \
man mans manpages htmpages unpack clean-unpack  changes.htm pdfs \
omf install-omf install-doc install-docs install-man3 install-mans \
upload-sourceforge www: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

sdl testsdl test-sdl install-sdl : ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

check-test0 check-test1 check-zzdir check-zzcat \
check-zzxor check-zzxordir check-zzxorcat \
check-sfx     check-readme : ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

test-comp: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

clean-comp: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

msvc : ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

zzip64-setup: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip64-setup.tmp : ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip64-build: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip64-build.tmp : ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip64-install: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip64-install.tmp : ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip32-postinstall: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"
zzip-postinstall: ; (cd $(BUILD) && $(ISNOTSRCDIR) && $(MAKE) "$@") || exit ; $(MAKE) done "RULE=$@"

done: ;@ if grep "$(RULE)-done .*:" Makefile > /dev/null; then     echo $(MAKE) $(RULE)-done ; $(MAKE) $(RULE)-done ; else true ; fi
PUB=pub/

auto:
	aclocal -I m4 && autoconf -I m4 && autoheader && automake

boottrap:
	rm -rf .deps .libs
	rm -f config.guess config.sub stamp-h.in
	rm -f install-sh ltconfig ltmain.sh depcomp mkinstalldirs
	rm -f config.h config.h.in config.log config.cache configure
	rm -f aclocal.m4 Makefile Makefile.in
	aclocal 
	autoconf 
	autoheader 
	automake -a -c 

rpm2: dist-bzip $(PACKAGE).spec
	rpmbuild -ta pub/$(PACKAGE)-$(VERSION).tar.bz2

dist-bzip : dist-bzip2
	$(MAKE) dist-bzip2-done
dist-bzip2-done dist-done :
	test -d $(PUB) || mkdir $(PUB)
	@ echo cp $(BUILD)/$(PACKAGE)-$(VERSION).tar.bz2 $(PUB). \
	;      cp $(BUILD)/$(PACKAGE)-$(VERSION).tar.bz2 $(PUB).
snapshot:
	$(MAKE) dist-bzip2 VERSION=`date +%Y.%m%d`
distclean-done:
	- rm -r *.d

configsub :
	cp ../savannah.config/config.guess uses/config.guess
	cp ../savannah.config/config.sub   uses/config.sub

